In [1]:
# Importing the necessary packages and modules.
import pandas as pd
import re

In [2]:
# Assigning the reading file directory and the output directory to variables.
path_original_data = "./Original_Datasets/"
path_output = "./New_Datasets/"

# Setting the default delimiter for output data files.
delimiter_file_result = ";"

# Creating the list of years of the datasets to be considered in the analysis, in descending order.
years_analysis = list(range(2023, 2014, -1))
# Organizing and storing information for reading the various .xlsx files of the original data.
# The three data for each analyzed year are:
# the file name,
# the spreadsheet name and
# the number of lines referring to the data header in that spreadsheet.
info_read_input_files = [
    ("DataForFigure2.1WHR2023.xls",
     "Sheet1",
     0,),
    ("Appendix_2_Data_for_Figure_2.1.xls",
     "2022",
     0,),
    ("DataForFigure2.1WHR2021C2.xls",
     "Sheet1",
     0,),
    ("WHR20_DataForFigure2.1.xls",
     "Sheet1",
     0,),
    ("Chapter2OnlineData.xls",
     "Figure2.6",
     0,),
    ("WHR2018Chapter2OnlineData.xls",
     "Figure2.2",
     0,),
    ("online-data-chapter-2-whr-2017.xlsx",
     "Figure2.2 WHR 2017",
     0,),
    ("Online-data-for-chapter-2-whr-2016.xlsx",
     "Figure2.2",
     0,),
    ("Chapter2OnlineData_Expanded-with-Trust-and-Governance.xlsx",
     "Data for Figure2.2",
     3,),
]

In [3]:
# Preparing the structure for storing the result data.
result_columns = ["COUNTRY", "REGION"]
table_results = pd.DataFrame(columns=result_columns)

In [4]:
# Function to identify, store, return and present the countries or regions among the original data
# that contain non-alphabetic characters.
def find_present_non_word_values(data_table=None,
                                 column_name=""):
    # If the original data file does not contain a country or region column, the function returns None.
    # Otherwise, the function returns the list of the data values that contain non-alphabetic characters.
    if column_name == "":
        return None
    else:
        # Presenting the list and total of unique values in the countries or regions column.
        print(data_table[column_name].unique())
        print(len(data_table[column_name].unique()))

        print("\n")

        # Identifying and storing the values among the data that contain non-alphabetic characters.
        values_column = data_table[column_name]
        values_column = values_column.map(arg=lambda value: re.findall(pattern=r"[^\w]+", string=value) if str(value) != "nan" else [])
        # Presenting information about the occurrence or not of values containing non-alphabetical characters
        # in the countries or regions column.
        print(len(values_column))
        print(values_column.index)
        print(values_column.describe())

        print("\n")

        # Filtering and storing the column values that contain non-alphabetic characters.
        values = []
        for i in range(len(values_column)):
            if len(values_column[i]) > 0:
                value = [i, data_table[column_name][i]]
                for j in range(len(values_column[i])):
                    value.append(values_column[i][j])
                value = tuple(value)
                values.append(value)
        # Presenting the vaues and the total values of the countries or regions column
        # that contain non-alphabetic characters.
        print(len(values))
        if len(values) > 0:
            for i in range(len(values)):
                print(values[i])

        # Returning the column values that contain non-alphabetic characters.
        return values

In [5]:
# Function for storing the list of countries from the original data files and their regions in the data result structure.
def include_data_table_results(data_table=None,
                               result_columns=[],
                               country_column_name="",
                               region_column_name="",
                               table_results=None):
    # Preparing the structure for temporary storage of the result data from one of the original data files.
    temp_table_results = pd.DataFrame(index=range(len(data_table)), columns=result_columns)

    # Storing the country names from original dataset or empty string in the temporary data storage structure.
    if country_column_name == "":
        temp_table_results[result_columns[0]] = [""] * len(data_table)
    else:
        temp_table_results[result_columns[0]] = data_table[country_column_name]

    # Storing the region names from original dataset or empty string in the temporary data storage structure.
    if region_column_name == "":
        temp_table_results[result_columns[1]] = [""] * len(data_table)
    else:
        temp_table_results[result_columns[1]] = data_table[region_column_name]

    # Concatenating data from one of the original data files to the result data structure with data of all input files.
    table_results = pd.concat(objs=[table_results, temp_table_results])
    table_results.index = range(len(table_results))
    
    # Presenting the result data structure.
    print(table_results)
    
    # Returning the result data structure.
    return table_results

In [6]:
# Collecting information to read the data file referring to the first year considered in the analysis (2023).
year_input_file = 0
input_file = path_original_data + str(years_analysis[year_input_file]) + "/" + info_read_input_files[year_input_file][0]
sheet_input_file = info_read_input_files[year_input_file][1]
line_header_input_file = info_read_input_files[year_input_file][2]

# Reading the data file referring to the first year considered in the analysis (2023).
data_table = pd.read_excel(io=input_file,
                           sheet_name=sheet_input_file,
                           header=line_header_input_file)

# Presenting the names and types of the columns of the data referring to the first year considered in the analysis (2023).
print(data_table.columns)
print(data_table.dtypes)

Index(['Country name', 'Ladder score', 'Standard error of ladder score',
       'upperwhisker', 'lowerwhisker', 'Logged GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],
      dtype='object')
Country name                                   object
Ladder score                                  float64
Standard error of ladder score                float64
upperwhisker                                  float64
lowerwhisker                                  float64
Logged GDP per capita                         float64
Social support                                float64
Healthy life expectancy                       float64
Freedom to make life choices                  float64
Generosity                                    float64
Perceptions of corruption                     float64
Ladder score in Dystopia                      float64
Explained by: Log GDP per capita              float64
Explained by: Social support                  float64
Explained by: Healthy life expectancy         float64
Explained by: Freedom to make life choices    float64
Explained by: Generosity                      float64
Explained by: Perceptions of corruption       float64
Dystopia + residual                           float64
dtype: object

In [7]:
# Storing the column names referring to the countries and regions data in the dataset for the year 2023.
country_column_name = "Country name"
region_column_name = ""

In [8]:
# Collecting, storing and presenting the values in the country column that contain non-alphabetic characters,
# referring to the data of year 2023.
values = find_present_non_word_values(data_table=data_table, column_name=country_column_name)

['Finland' 'Denmark' 'Iceland' 'Israel' 'Netherlands' 'Sweden' 'Norway'
 'Switzerland' 'Luxembourg' 'New Zealand' 'Austria' 'Australia' 'Canada'
 'Ireland' 'United States' 'Germany' 'Belgium' 'Czechia' 'United Kingdom'
 'Lithuania' 'France' 'Slovenia' 'Costa Rica' 'Romania' 'Singapore'
 'United Arab Emirates' 'Taiwan Province of China' 'Uruguay' 'Slovakia'
 'Saudi Arabia' 'Estonia' 'Spain' 'Italy' 'Kosovo' 'Chile' 'Mexico'
 'Malta' 'Panama' 'Poland' 'Nicaragua' 'Latvia' 'Bahrain' 'Guatemala'
 'Kazakhstan' 'Serbia' 'Cyprus' 'Japan' 'Croatia' 'Brazil' 'El Salvador'
 'Hungary' 'Argentina' 'Honduras' 'Uzbekistan' 'Malaysia' 'Portugal'
 'South Korea' 'Greece' 'Mauritius' 'Thailand' 'Mongolia' 'Kyrgyzstan'
 'Moldova' 'China' 'Vietnam' 'Paraguay' 'Montenegro' 'Jamaica' 'Bolivia'
 'Russia' 'Bosnia and Herzegovina' 'Colombia' 'Dominican Republic'
 'Ecuador' 'Peru' 'Philippines' 'Bulgaria' 'Nepal' 'Armenia' 'Tajikistan'
 'Algeria' 'Hong Kong S.A.R. of China' 'Albania' 'Indonesia'
 'South Africa' 'Congo (Brazzaville)' 'North Macedonia' 'Venezuela' 'Laos'
 'Georgia' 'Guinea' 'Ukraine' 'Ivory Coast' 'Gabon' 'Nigeria' 'Cameroon'
 'Mozambique' 'Iraq' 'State of Palestine' 'Morocco' 'Iran' 'Senegal'
 'Mauritania' 'Burkina Faso' 'Namibia' 'Turkiye' 'Ghana' 'Pakistan'
 'Niger' 'Tunisia' 'Kenya' 'Sri Lanka' 'Uganda' 'Chad' 'Cambodia' 'Benin'
 'Myanmar' 'Bangladesh' 'Gambia' 'Mali' 'Egypt' 'Togo' 'Jordan' 'Ethiopia'
 'Liberia' 'India' 'Madagascar' 'Zambia' 'Tanzania' 'Comoros' 'Malawi'
 'Botswana' 'Congo (Kinshasa)' 'Zimbabwe' 'Sierra Leone' 'Lebanon'
 'Afghanistan']
137


137
RangeIndex(start=0, stop=137, step=1)
count     137
unique      6
top        []
freq      116
Name: Country name, dtype: object


21
(9, 'New Zealand', ' ')
(14, 'United States', ' ')
(18, 'United Kingdom', ' ')
(22, 'Costa Rica', ' ')
(25, 'United Arab Emirates', ' ', ' ')
(26, 'Taiwan Province of China', ' ', ' ', ' ')
(29, 'Saudi Arabia', ' ')
(49, 'El Salvador', ' ')
(56, 'South Korea', ' ')
(70, 'Bosnia and Herzegovina', ' ', ' ')
(72, 'Dominican Republic', ' ')
(81, 'Hong Kong S.A.R. of China', ' ', ' ', '.', '.', '. ', ' ')
(84, 'South Africa', ' ')
(85, 'Congo (Brazzaville)', ' (', ')')
(86, 'North Macedonia', ' ')
(92, 'Ivory Coast', ' ')
(98, 'State of Palestine', ' ', ' ')
(103, 'Burkina Faso', ' ')
(111, 'Sri Lanka', ' ')
(132, 'Congo (Kinshasa)', ' (', ')')
(134, 'Sierra Leone', ' ')

In [9]:
# Collecting, storing and presenting the values in the region column that contain non-alphabetic characters,
# referring to the data of year 2023.
values = find_present_non_word_values(data_table=data_table, column_name=region_column_name)

In [10]:
# Storing country and region data of year 2023 in the result data structure.
table_results = include_data_table_results(data_table=data_table,
                                           result_columns=result_columns,
                                           country_column_name=country_column_name,
                                           region_column_name=region_column_name,
                                           table_results=table_results)

              COUNTRY REGION
0             Finland
1             Denmark
2             Iceland
3              Israel
4         Netherlands
..                ...    ...
132  Congo (Kinshasa)
133          Zimbabwe
134      Sierra Leone
135           Lebanon
136       Afghanistan

[137 rows x 2 columns]

In [11]:
# Collecting information to read the data file referring to the first year considered in the analysis (2022).
year_input_file = 1
input_file = path_original_data + str(years_analysis[year_input_file]) + "/" + info_read_input_files[year_input_file][0]
sheet_input_file = info_read_input_files[year_input_file][1]
line_header_input_file = info_read_input_files[year_input_file][2]

# Reading the data file referring to the first year considered in the analysis (2022).
data_table = pd.read_excel(io=input_file,
                           sheet_name=sheet_input_file,
                           header=line_header_input_file)

# Presenting the names and types of the columns of the data referring to the first year considered in the analysis (2022).
print(data_table.columns)
print(data_table.dtypes)

Index(['RANK', 'Country', 'Happiness score', 'Whisker-high', 'Whisker-low',
       'Dystopia (1.83) + residual', 'Explained by: GDP per capita',
       'Explained by: Social support', 'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption'],
      dtype='object')
RANK                                            int64
Country                                        object
Happiness score                               float64
Whisker-high                                  float64
Whisker-low                                   float64
Dystopia (1.83) + residual                    float64
Explained by: GDP per capita                  float64
Explained by: Social support                  float64
Explained by: Healthy life expectancy         float64
Explained by: Freedom to make life choices    float64
Explained by: Generosity                      float64
Explained by: Perceptions of corruption       float64
dtype: object

In [12]:
# Storing the column names referring to the countries and regions data in the dataset for the year 2022.
country_column_name = "Country"
region_column_name = ""

In [13]:
# Collecting, storing and presenting the values in the country column that contain non-alphabetic characters,
# referring to the data of year 2022.
values = find_present_non_word_values(data_table=data_table, column_name=country_column_name)

['Finland' 'Denmark' 'Iceland' 'Switzerland' 'Netherlands' 'Luxembourg*'
 'Sweden' 'Norway' 'Israel' 'New Zealand' 'Austria' 'Australia' 'Ireland'
 'Germany' 'Canada' 'United States' 'United Kingdom' 'Czechia' 'Belgium'
 'France' 'Bahrain' 'Slovenia' 'Costa Rica' 'United Arab Emirates'
 'Saudi Arabia' 'Taiwan Province of China' 'Singapore' 'Romania' 'Spain'
 'Uruguay' 'Italy' 'Kosovo' 'Malta' 'Lithuania' 'Slovakia' 'Estonia'
 'Panama' 'Brazil' 'Guatemala*' 'Kazakhstan' 'Cyprus' 'Latvia' 'Serbia'
 'Chile' 'Nicaragua' 'Mexico' 'Croatia' 'Poland' 'El Salvador' 'Kuwait*'
 'Hungary' 'Mauritius' 'Uzbekistan' 'Japan' 'Honduras' 'Portugal'
 'Argentina' 'Greece' 'South Korea' 'Philippines' 'Thailand' 'Moldova'
 'Jamaica' 'Kyrgyzstan' 'Belarus*' 'Colombia' 'Bosnia and Herzegovina'
 'Mongolia' 'Dominican Republic' 'Malaysia' 'Bolivia' 'China' 'Paraguay'
 'Peru' 'Montenegro' 'Ecuador' 'Vietnam' 'Turkmenistan*' 'North Cyprus*'
 'Russia' 'Hong Kong S.A.R. of China' 'Armenia' 'Tajikistan' 'Nepal'
 'Bulgaria' 'Libya*' 'Indonesia' 'Ivory Coast' 'North Macedonia' 'Albania'
 'South Africa' 'Azerbaijan*' 'Gambia*' 'Bangladesh' 'Laos' 'Algeria'
 'Liberia*' 'Ukraine' 'Congo' 'Morocco' 'Mozambique' 'Cameroon' 'Senegal'
 'Niger*' 'Georgia' 'Gabon' 'Iraq' 'Venezuela' 'Guinea' 'Iran' 'Ghana'
 'Turkey' 'Burkina Faso' 'Cambodia' 'Benin' 'Comoros*' 'Uganda' 'Nigeria'
 'Kenya' 'Tunisia' 'Pakistan' 'Palestinian Territories*' 'Mali' 'Namibia'
 'Eswatini, Kingdom of*' 'Myanmar' 'Sri Lanka' 'Madagascar*' 'Egypt'
 'Chad*' 'Ethiopia' 'Yemen*' 'Mauritania*' 'Jordan' 'Togo' 'India'
 'Zambia' 'Malawi' 'Tanzania' 'Sierra Leone' 'Lesotho*' 'Botswana*'
 'Rwanda*' 'Zimbabwe' 'Lebanon' 'Afghanistan' 'xx']
147


147
RangeIndex(start=0, stop=147, step=1)
count     147
unique      8
top        []
freq      108
Name: Country, dtype: object


39
(5, 'Luxembourg*', '*')
(9, 'New Zealand', ' ')
(15, 'United States', ' ')
(16, 'United Kingdom', ' ')
(22, 'Costa Rica', ' ')
(23, 'United Arab Emirates', ' ', ' ')
(24, 'Saudi Arabia', ' ')
(25, 'Taiwan Province of China', ' ', ' ', ' ')
(38, 'Guatemala*', '*')
(48, 'El Salvador', ' ')
(49, 'Kuwait*', '*')
(58, 'South Korea', ' ')
(64, 'Belarus*', '*')
(66, 'Bosnia and Herzegovina', ' ', ' ')
(68, 'Dominican Republic', ' ')
(77, 'Turkmenistan*', '*')
(78, 'North Cyprus*', ' ', '*')
(80, 'Hong Kong S.A.R. of China', ' ', ' ', '.', '.', '. ', ' ')
(85, 'Libya*', '*')
(87, 'Ivory Coast', ' ')
(88, 'North Macedonia', ' ')
(90, 'South Africa', ' ')
(91, 'Azerbaijan*', '*')
(92, 'Gambia*', '*')
(96, 'Liberia*', '*')
(103, 'Niger*', '*')
(112, 'Burkina Faso', ' ')
(115, 'Comoros*', '*')
(121, 'Palestinian Territories*', ' ', '*')
(124, 'Eswatini, Kingdom of*', ', ', ' ', '*')
(126, 'Sri Lanka', ' ')
(127, 'Madagascar*', '*')
(129, 'Chad*', '*')
(131, 'Yemen*', '*')
(132, 'Mauritania*', '*')
(139, 'Sierra Leone', ' ')
(140, 'Lesotho*', '*')
(141, 'Botswana*', '*')
(142, 'Rwanda*', '*')

In [14]:
# Changing the values for country data referring to the year 2022 that contain non-alphabetic characters,
# in the result data structure.
indices_to_change = []
new_values = []

# For the year 2022, countries that contain the * character, it will be removed from the value.
for i in range(len(values)):
    if values[i][1][-1] == "*":
        indices_to_change.append(values[i][0])
        new_values.append(values[i][1][0:-1])
# The "Eswatini, Kingdom of" value will be reformatted.
indices_to_change.append(124)
new_values.append("Kingdom of Eswatini")

# Presenting the new values.
print(indices_to_change)
print(new_values)
print(len(indices_to_change))
print(len(new_values))

# Changing the identifies values in the result data structure.
for i in range(len(indices_to_change)):
    data_table.loc[indices_to_change[i], country_column_name] = new_values[i]

# Presenting the new values in the result data structure.
print(data_table[country_column_name][indices_to_change])

[5, 38, 49, 64, 77, 78, 85, 91, 92, 96, 103, 115, 121, 124, 127, 129, 131, 132, 140, 141, 142, 124]
['Luxembourg', 'Guatemala', 'Kuwait', 'Belarus', 'Turkmenistan', 'North Cyprus', 'Libya', 'Azerbaijan', 'Gambia', 'Liberia', 'Niger', 'Comoros', 'Palestinian Territories', 'Eswatini, Kingdom of', 'Madagascar', 'Chad', 'Yemen', 'Mauritania', 'Lesotho', 'Botswana', 'Rwanda', 'Kingdom of Eswatini']
22
22
5                   Luxembourg
38                   Guatemala
49                      Kuwait
64                     Belarus
77                Turkmenistan
78                North Cyprus
85                       Libya
91                  Azerbaijan
92                      Gambia
96                     Liberia
103                      Niger
115                    Comoros
121    Palestinian Territories
124        Kingdom of Eswatini
127                 Madagascar
129                       Chad
131                      Yemen
132                 Mauritania
140                    Lesotho
141                   Botswana
142                     Rwanda
124        Kingdom of Eswatini
Name: Country, dtype: object

In [15]:
# Collecting, storing and presenting the values in the region column that contain non-alphabetic characters,
# referring to the data of year 2022.
values = find_present_non_word_values(data_table=data_table, column_name=region_column_name)

In [16]:
# Storing country and region data of year 2022 in the result data structure.
table_results = include_data_table_results(data_table=data_table,
                                           result_columns=result_columns,
                                           country_column_name=country_column_name,
                                           region_column_name=region_column_name,
                                           table_results=table_results)

         COUNTRY REGION
0        Finland
1        Denmark
2        Iceland
3         Israel
4    Netherlands
..           ...    ...
279       Rwanda
280     Zimbabwe
281      Lebanon
282  Afghanistan
283           xx

[284 rows x 2 columns]

In [17]:
# Collecting information to read the data file referring to the first year considered in the analysis (2021).
year_input_file = 2
input_file = path_original_data + str(years_analysis[year_input_file]) + "/" + info_read_input_files[year_input_file][0]
sheet_input_file = info_read_input_files[year_input_file][1]
line_header_input_file = info_read_input_files[year_input_file][2]

# Reading the data file referring to the first year considered in the analysis (2021).
data_table = pd.read_excel(io=input_file,
                           sheet_name=sheet_input_file,
                           header=line_header_input_file)

# Presenting the names and types of the columns of the data referring to the first year considered in the analysis (2021).
print(data_table.columns)
print(data_table.dtypes)

Index(['Country name', 'Regional indicator', 'Ladder score',
       'Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],
      dtype='object')
Country name                                   object
Regional indicator                             object
Ladder score                                  float64
Standard error of ladder score                float64
upperwhisker                                  float64
lowerwhisker                                  float64
Logged GDP per capita                         float64
Social support                                float64
Healthy life expectancy                       float64
Freedom to make life choices                  float64
Generosity                                    float64
Perceptions of corruption                     float64
Ladder score in Dystopia                      float64
Explained by: Log GDP per capita              float64
Explained by: Social support                  float64
Explained by: Healthy life expectancy         float64
Explained by: Freedom to make life choices    float64
Explained by: Generosity                      float64
Explained by: Perceptions of corruption       float64
Dystopia + residual                           float64
dtype: object

In [18]:
# Storing the column names referring to the countries and regions data in the dataset for the year 2021.
country_column_name = "Country name"
region_column_name = "Regional indicator"

In [19]:
# Collecting, storing and presenting the values in the country column that contain non-alphabetic characters,
# referring to the data of year 2021.
values = find_present_non_word_values(data_table=data_table, column_name=country_column_name)

['Finland' 'Denmark' 'Switzerland' 'Iceland' 'Netherlands' 'Norway'
 'Sweden' 'Luxembourg' 'New Zealand' 'Austria' 'Australia' 'Israel'
 'Germany' 'Canada' 'Ireland' 'Costa Rica' 'United Kingdom'
 'Czech Republic' 'United States' 'Belgium' 'France' 'Bahrain' 'Malta'
 'Taiwan Province of China' 'United Arab Emirates' 'Saudi Arabia' 'Spain'
 'Italy' 'Slovenia' 'Guatemala' 'Uruguay' 'Singapore' 'Kosovo' 'Slovakia'
 'Brazil' 'Mexico' 'Jamaica' 'Lithuania' 'Cyprus' 'Estonia' 'Panama'
 'Uzbekistan' 'Chile' 'Poland' 'Kazakhstan' 'Romania' 'Kuwait' 'Serbia'
 'El Salvador' 'Mauritius' 'Latvia' 'Colombia' 'Hungary' 'Thailand'
 'Nicaragua' 'Japan' 'Argentina' 'Portugal' 'Honduras' 'Croatia'
 'Philippines' 'South Korea' 'Peru' 'Bosnia and Herzegovina' 'Moldova'
 'Ecuador' 'Kyrgyzstan' 'Greece' 'Bolivia' 'Mongolia' 'Paraguay'
 'Montenegro' 'Dominican Republic' 'North Cyprus' 'Belarus' 'Russia'
 'Hong Kong S.A.R. of China' 'Tajikistan' 'Vietnam' 'Libya' 'Malaysia'
 'Indonesia' 'Congo (Brazzaville)' 'China' 'Ivory Coast' 'Armenia' 'Nepal'
 'Bulgaria' 'Maldives' 'Azerbaijan' 'Cameroon' 'Senegal' 'Albania'
 'North Macedonia' 'Ghana' 'Niger' 'Turkmenistan' 'Gambia' 'Benin' 'Laos'
 'Bangladesh' 'Guinea' 'South Africa' 'Turkey' 'Pakistan' 'Morocco'
 'Venezuela' 'Georgia' 'Algeria' 'Ukraine' 'Iraq' 'Gabon' 'Burkina Faso'
 'Cambodia' 'Mozambique' 'Nigeria' 'Mali' 'Iran' 'Uganda' 'Liberia'
 'Kenya' 'Tunisia' 'Lebanon' 'Namibia' 'Palestinian Territories' 'Myanmar'
 'Jordan' 'Chad' 'Sri Lanka' 'Swaziland' 'Comoros' 'Egypt' 'Ethiopia'
 'Mauritania' 'Madagascar' 'Togo' 'Zambia' 'Sierra Leone' 'India'
 'Burundi' 'Yemen' 'Tanzania' 'Haiti' 'Malawi' 'Lesotho' 'Botswana'
 'Rwanda' 'Zimbabwe' 'Afghanistan']
149


149
RangeIndex(start=0, stop=149, step=1)
count     149
unique      6
top        []
freq      127
Name: Country name, dtype: object


22
(8, 'New Zealand', ' ')
(15, 'Costa Rica', ' ')
(16, 'United Kingdom', ' ')
(17, 'Czech Republic', ' ')
(18, 'United States', ' ')
(23, 'Taiwan Province of China', ' ', ' ', ' ')
(24, 'United Arab Emirates', ' ', ' ')
(25, 'Saudi Arabia', ' ')
(48, 'El Salvador', ' ')
(61, 'South Korea', ' ')
(63, 'Bosnia and Herzegovina', ' ', ' ')
(72, 'Dominican Republic', ' ')
(73, 'North Cyprus', ' ')
(76, 'Hong Kong S.A.R. of China', ' ', ' ', '.', '.', '. ', ' ')
(82, 'Congo (Brazzaville)', ' (', ')')
(84, 'Ivory Coast', ' ')
(93, 'North Macedonia', ' ')
(102, 'South Africa', ' ')
(112, 'Burkina Faso', ' ')
(124, 'Palestinian Territories', ' ')
(128, 'Sri Lanka', ' ')
(137, 'Sierra Leone', ' ')

In [20]:
# Collecting, storing and presenting the values in the region column that contain non-alphabetic characters,
# referring to the data of year 2021.
values = find_present_non_word_values(data_table=data_table, column_name=region_column_name)

['Western Europe' 'North America and ANZ' 'Middle East and North Africa'
 'Latin America and Caribbean' 'Central and Eastern Europe' 'East Asia'
 'Southeast Asia' 'Commonwealth of Independent States'
 'Sub-Saharan Africa' 'South Asia']
10


149
RangeIndex(start=0, stop=149, step=1)
count           149
unique            4
top       [ ,  ,  ]
freq             53
Name: Regional indicator, dtype: object


149
(0, 'Western Europe', ' ')
(1, 'Western Europe', ' ')
(2, 'Western Europe', ' ')
(3, 'Western Europe', ' ')
(4, 'Western Europe', ' ')
(5, 'Western Europe', ' ')
(6, 'Western Europe', ' ')
(7, 'Western Europe', ' ')
(8, 'North America and ANZ', ' ', ' ', ' ')
(9, 'Western Europe', ' ')
(10, 'North America and ANZ', ' ', ' ', ' ')
(11, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(12, 'Western Europe', ' ')
(13, 'North America and ANZ', ' ', ' ', ' ')
(14, 'Western Europe', ' ')
(15, 'Latin America and Caribbean', ' ', ' ', ' ')
(16, 'Western Europe', ' ')
(17, 'Central and Eastern Europe', ' ', ' ', ' ')
(18, 'North America and ANZ', ' ', ' ', ' ')
(19, 'Western Europe', ' ')
(20, 'Western Europe', ' ')
(21, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(22, 'Western Europe', ' ')
(23, 'East Asia', ' ')
(24, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(25, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(26, 'Western Europe', ' ')
(27, 'Western Europe', ' ')
(28, 'Central and Eastern Europe', ' ', ' ', ' ')
(29, 'Latin America and Caribbean', ' ', ' ', ' ')
(30, 'Latin America and Caribbean', ' ', ' ', ' ')
(31, 'Southeast Asia', ' ')
(32, 'Central and Eastern Europe', ' ', ' ', ' ')
(33, 'Central and Eastern Europe', ' ', ' ', ' ')
(34, 'Latin America and Caribbean', ' ', ' ', ' ')
(35, 'Latin America and Caribbean', ' ', ' ', ' ')
(36, 'Latin America and Caribbean', ' ', ' ', ' ')
(37, 'Central and Eastern Europe', ' ', ' ', ' ')
(38, 'Western Europe', ' ')
(39, 'Central and Eastern Europe', ' ', ' ', ' ')
(40, 'Latin America and Caribbean', ' ', ' ', ' ')
(41, 'Commonwealth of Independent States', ' ', ' ', ' ')
(42, 'Latin America and Caribbean', ' ', ' ', ' ')
(43, 'Central and Eastern Europe', ' ', ' ', ' ')
(44, 'Commonwealth of Independent States', ' ', ' ', ' ')
(45, 'Central and Eastern Europe', ' ', ' ', ' ')
(46, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(47, 'Central and Eastern Europe', ' ', ' ', ' ')
(48, 'Latin America and Caribbean', ' ', ' ', ' ')
(49, 'Sub-Saharan Africa', '-', ' ')
(50, 'Central and Eastern Europe', ' ', ' ', ' ')
(51, 'Latin America and Caribbean', ' ', ' ', ' ')
(52, 'Central and Eastern Europe', ' ', ' ', ' ')
(53, 'Southeast Asia', ' ')
(54, 'Latin America and Caribbean', ' ', ' ', ' ')
(55, 'East Asia', ' ')
(56, 'Latin America and Caribbean', ' ', ' ', ' ')
(57, 'Western Europe', ' ')
(58, 'Latin America and Caribbean', ' ', ' ', ' ')
(59, 'Central and Eastern Europe', ' ', ' ', ' ')
(60, 'Southeast Asia', ' ')
(61, 'East Asia', ' ')
(62, 'Latin America and Caribbean', ' ', ' ', ' ')
(63, 'Central and Eastern Europe', ' ', ' ', ' ')
(64, 'Commonwealth of Independent States', ' ', ' ', ' ')
(65, 'Latin America and Caribbean', ' ', ' ', ' ')
(66, 'Commonwealth of Independent States', ' ', ' ', ' ')
(67, 'Western Europe', ' ')
(68, 'Latin America and Caribbean', ' ', ' ', ' ')
(69, 'East Asia', ' ')
(70, 'Latin America and Caribbean', ' ', ' ', ' ')
(71, 'Central and Eastern Europe', ' ', ' ', ' ')
(72, 'Latin America and Caribbean', ' ', ' ', ' ')
(73, 'Western Europe', ' ')
(74, 'Commonwealth of Independent States', ' ', ' ', ' ')
(75, 'Commonwealth of Independent States', ' ', ' ', ' ')
(76, 'East Asia', ' ')
(77, 'Commonwealth of Independent States', ' ', ' ', ' ')
(78, 'Southeast Asia', ' ')
(79, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(80, 'Southeast Asia', ' ')
(81, 'Southeast Asia', ' ')
(82, 'Sub-Saharan Africa', '-', ' ')
(83, 'East Asia', ' ')
(84, 'Sub-Saharan Africa', '-', ' ')
(85, 'Commonwealth of Independent States', ' ', ' ', ' ')
(86, 'South Asia', ' ')
(87, 'Central and Eastern Europe', ' ', ' ', ' ')
(88, 'South Asia', ' ')
(89, 'Commonwealth of Independent States', ' ', ' ', ' ')
(90, 'Sub-Saharan Africa', '-', ' ')
(91, 'Sub-Saharan Africa', '-', ' ')
(92, 'Central and Eastern Europe', ' ', ' ', ' ')
(93, 'Central and Eastern Europe', ' ', ' ', ' ')
(94, 'Sub-Saharan Africa', '-', ' ')
(95, 'Sub-Saharan Africa', '-', ' ')
(96, 'Commonwealth of Independent States', ' ', ' ', ' ')
(97, 'Sub-Saharan Africa', '-', ' ')
(98, 'Sub-Saharan Africa', '-', ' ')
(99, 'Southeast Asia', ' ')
(100, 'South Asia', ' ')
(101, 'Sub-Saharan Africa', '-', ' ')
(102, 'Sub-Saharan Africa', '-', ' ')
(103, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(104, 'South Asia', ' ')
(105, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(106, 'Latin America and Caribbean', ' ', ' ', ' ')
(107, 'Commonwealth of Independent States', ' ', ' ', ' ')
(108, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(109, 'Commonwealth of Independent States', ' ', ' ', ' ')
(110, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(111, 'Sub-Saharan Africa', '-', ' ')
(112, 'Sub-Saharan Africa', '-', ' ')
(113, 'Southeast Asia', ' ')
(114, 'Sub-Saharan Africa', '-', ' ')
(115, 'Sub-Saharan Africa', '-', ' ')
(116, 'Sub-Saharan Africa', '-', ' ')
(117, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(118, 'Sub-Saharan Africa', '-', ' ')
(119, 'Sub-Saharan Africa', '-', ' ')
(120, 'Sub-Saharan Africa', '-', ' ')
(121, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(122, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(123, 'Sub-Saharan Africa', '-', ' ')
(124, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(125, 'Southeast Asia', ' ')
(126, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(127, 'Sub-Saharan Africa', '-', ' ')
(128, 'South Asia', ' ')
(129, 'Sub-Saharan Africa', '-', ' ')
(130, 'Sub-Saharan Africa', '-', ' ')
(131, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(132, 'Sub-Saharan Africa', '-', ' ')
(133, 'Sub-Saharan Africa', '-', ' ')
(134, 'Sub-Saharan Africa', '-', ' ')
(135, 'Sub-Saharan Africa', '-', ' ')
(136, 'Sub-Saharan Africa', '-', ' ')
(137, 'Sub-Saharan Africa', '-', ' ')
(138, 'South Asia', ' ')
(139, 'Sub-Saharan Africa', '-', ' ')
(140, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(141, 'Sub-Saharan Africa', '-', ' ')
(142, 'Latin America and Caribbean', ' ', ' ', ' ')
(143, 'Sub-Saharan Africa', '-', ' ')
(144, 'Sub-Saharan Africa', '-', ' ')
(145, 'Sub-Saharan Africa', '-', ' ')
(146, 'Sub-Saharan Africa', '-', ' ')
(147, 'Sub-Saharan Africa', '-', ' ')
(148, 'South Asia', ' ')

In [21]:
# Presenting the unique values in the region column, to identify necessary changes.
list(data_table[region_column_name].unique())

['Western Europe',
 'North America and ANZ',
 'Middle East and North Africa',
 'Latin America and Caribbean',
 'Central and Eastern Europe',
 'East Asia',
 'Southeast Asia',
 'Commonwealth of Independent States',
 'Sub-Saharan Africa',
 'South Asia']

In [22]:
# Checking and presenting which non-alphabetic characters are contained among the values and
# the respective values to identify possible changes.
for i in range(len(values)):
    if len(values[i]) > 2:
        found = False
        for j in range(2, len(values[i])):
            if values[i][j] != " ":
                found = True
                break
        if found:
            value = str(values[i][0]) + " -- "
            value += values[i][1] + " -- "
            for j in range(2, len(values[i])):
                if values[i][j] != " ":
                    value += values[i][j] + " -- "
            value = value[0:-4]
            print(value)

49 -- Sub-Saharan Africa -- -
82 -- Sub-Saharan Africa -- -
84 -- Sub-Saharan Africa -- -
90 -- Sub-Saharan Africa -- -
91 -- Sub-Saharan Africa -- -
94 -- Sub-Saharan Africa -- -
95 -- Sub-Saharan Africa -- -
97 -- Sub-Saharan Africa -- -
98 -- Sub-Saharan Africa -- -
101 -- Sub-Saharan Africa -- -
102 -- Sub-Saharan Africa -- -
111 -- Sub-Saharan Africa -- -
112 -- Sub-Saharan Africa -- -
114 -- Sub-Saharan Africa -- -
115 -- Sub-Saharan Africa -- -
116 -- Sub-Saharan Africa -- -
118 -- Sub-Saharan Africa -- -
119 -- Sub-Saharan Africa -- -
120 -- Sub-Saharan Africa -- -
123 -- Sub-Saharan Africa -- -
127 -- Sub-Saharan Africa -- -
129 -- Sub-Saharan Africa -- -
130 -- Sub-Saharan Africa -- -
132 -- Sub-Saharan Africa -- -
133 -- Sub-Saharan Africa -- -
134 -- Sub-Saharan Africa -- -
135 -- Sub-Saharan Africa -- -
136 -- Sub-Saharan Africa -- -
137 -- Sub-Saharan Africa -- -
139 -- Sub-Saharan Africa -- -
141 -- Sub-Saharan Africa -- -
143 -- Sub-Saharan Africa -- -
144 -- Sub-Saharan Africa -- -
145 -- Sub-Saharan Africa -- -
146 -- Sub-Saharan Africa -- -
147 -- Sub-Saharan Africa -- -

In [23]:
# Storing country and region data of year 2021 in the result data structure.
table_results = include_data_table_results(data_table=data_table,
                                           result_columns=result_columns,
                                           country_column_name=country_column_name,
                                           region_column_name=region_column_name,
                                           table_results=table_results)

         COUNTRY              REGION
0        Finland
1        Denmark
2        Iceland
3         Israel
4    Netherlands
..           ...                 ...
428      Lesotho  Sub-Saharan Africa
429     Botswana  Sub-Saharan Africa
430       Rwanda  Sub-Saharan Africa
431     Zimbabwe  Sub-Saharan Africa
432  Afghanistan          South Asia

[433 rows x 2 columns]

In [24]:
# Collecting information to read the data file referring to the first year considered in the analysis (2020).
year_input_file = 3
input_file = path_original_data + str(years_analysis[year_input_file]) + "/" + info_read_input_files[year_input_file][0]
sheet_input_file = info_read_input_files[year_input_file][1]
line_header_input_file = info_read_input_files[year_input_file][2]

# Reading the data file referring to the first year considered in the analysis (2020).
data_table = pd.read_excel(io=input_file,
                           sheet_name=sheet_input_file,
                           header=line_header_input_file)

# Presenting the names and types of the columns of the data referring to the first year considered in the analysis (2020).
print(data_table.columns)
print(data_table.dtypes)

Index(['Country name', 'Regional indicator', 'Ladder score',
       'Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],
      dtype='object')
Country name                                   object
Regional indicator                             object
Ladder score                                  float64
Standard error of ladder score                float64
upperwhisker                                  float64
lowerwhisker                                  float64
Logged GDP per capita                         float64
Social support                                float64
Healthy life expectancy                       float64
Freedom to make life choices                  float64
Generosity                                    float64
Perceptions of corruption                     float64
Ladder score in Dystopia                      float64
Explained by: Log GDP per capita              float64
Explained by: Social support                  float64
Explained by: Healthy life expectancy         float64
Explained by: Freedom to make life choices    float64
Explained by: Generosity                      float64
Explained by: Perceptions of corruption       float64
Dystopia + residual                           float64
dtype: object

In [25]:
# Storing the column names referring to the countries and regions data in the dataset for the year 2020.
country_column_name = "Country name"
region_column_name = "Regional indicator"

In [26]:
# Collecting, storing and presenting the values in the country column that contain non-alphabetic characters,
# referring to the data of year 2020.
values = find_present_non_word_values(data_table=data_table, column_name=country_column_name)

['Finland' 'Denmark' 'Switzerland' 'Iceland' 'Norway' 'Netherlands'
 'Sweden' 'New Zealand' 'Austria' 'Luxembourg' 'Canada' 'Australia'
 'United Kingdom' 'Israel' 'Costa Rica' 'Ireland' 'Germany'
 'United States' 'Czech Republic' 'Belgium' 'United Arab Emirates' 'Malta'
 'France' 'Mexico' 'Taiwan Province of China' 'Uruguay' 'Saudi Arabia'
 'Spain' 'Guatemala' 'Italy' 'Singapore' 'Brazil' 'Slovenia' 'El Salvador'
 'Kosovo' 'Panama' 'Slovakia' 'Uzbekistan' 'Chile' 'Bahrain' 'Lithuania'
 'Trinidad and Tobago' 'Poland' 'Colombia' 'Cyprus' 'Nicaragua' 'Romania'
 'Kuwait' 'Mauritius' 'Kazakhstan' 'Estonia' 'Philippines' 'Hungary'
 'Thailand' 'Argentina' 'Honduras' 'Latvia' 'Ecuador' 'Portugal' 'Jamaica'
 'South Korea' 'Japan' 'Peru' 'Serbia' 'Bolivia' 'Pakistan' 'Paraguay'
 'Dominican Republic' 'Bosnia and Herzegovina' 'Moldova' 'Tajikistan'
 'Montenegro' 'Russia' 'Kyrgyzstan' 'Belarus' 'North Cyprus' 'Greece'
 'Hong Kong S.A.R. of China' 'Croatia' 'Libya' 'Mongolia' 'Malaysia'
 'Vietnam' 'Indonesia' 'Ivory Coast' 'Benin' 'Maldives'
 'Congo (Brazzaville)' 'Azerbaijan' 'Macedonia' 'Ghana' 'Nepal' 'Turkey'
 'China' 'Turkmenistan' 'Bulgaria' 'Morocco' 'Cameroon' 'Venezuela'
 'Algeria' 'Senegal' 'Guinea' 'Niger' 'Laos' 'Albania' 'Cambodia'
 'Bangladesh' 'Gabon' 'South Africa' 'Iraq' 'Lebanon' 'Burkina Faso'
 'Gambia' 'Mali' 'Nigeria' 'Armenia' 'Georgia' 'Iran' 'Jordan'
 'Mozambique' 'Kenya' 'Namibia' 'Ukraine' 'Liberia'
 'Palestinian Territories' 'Uganda' 'Chad' 'Tunisia' 'Mauritania'
 'Sri Lanka' 'Congo (Kinshasa)' 'Swaziland' 'Myanmar' 'Comoros' 'Togo'
 'Ethiopia' 'Madagascar' 'Egypt' 'Sierra Leone' 'Burundi' 'Zambia' 'Haiti'
 'Lesotho' 'India' 'Malawi' 'Yemen' 'Botswana' 'Tanzania'
 'Central African Republic' 'Rwanda' 'Zimbabwe' 'South Sudan'
 'Afghanistan']
153


153
RangeIndex(start=0, stop=153, step=1)
count     153
unique      6
top        []
freq      128
Name: Country name, dtype: object


25
(7, 'New Zealand', ' ')
(12, 'United Kingdom', ' ')
(14, 'Costa Rica', ' ')
(17, 'United States', ' ')
(18, 'Czech Republic', ' ')
(20, 'United Arab Emirates', ' ', ' ')
(24, 'Taiwan Province of China', ' ', ' ', ' ')
(26, 'Saudi Arabia', ' ')
(33, 'El Salvador', ' ')
(41, 'Trinidad and Tobago', ' ', ' ')
(60, 'South Korea', ' ')
(67, 'Dominican Republic', ' ')
(68, 'Bosnia and Herzegovina', ' ', ' ')
(75, 'North Cyprus', ' ')
(77, 'Hong Kong S.A.R. of China', ' ', ' ', '.', '.', '. ', ' ')
(84, 'Ivory Coast', ' ')
(87, 'Congo (Brazzaville)', ' (', ')')
(108, 'South Africa', ' ')
(111, 'Burkina Faso', ' ')
(124, 'Palestinian Territories', ' ')
(129, 'Sri Lanka', ' ')
(130, 'Congo (Kinshasa)', ' (', ')')
(138, 'Sierra Leone', ' ')
(148, 'Central African Republic', ' ', ' ')
(151, 'South Sudan', ' ')

In [27]:
# Collecting, storing and presenting the values in the region column that contain non-alphabetic characters,
# referring to the data of year 2020.
values = find_present_non_word_values(data_table=data_table, column_name=region_column_name)

['Western Europe' 'North America and ANZ' 'Middle East and North Africa'
 'Latin America and Caribbean' 'Central and Eastern Europe' 'East Asia'
 'Southeast Asia' 'Commonwealth of Independent States'
 'Sub-Saharan Africa' 'South Asia']
10


153
RangeIndex(start=0, stop=153, step=1)
count           153
unique            4
top       [ ,  ,  ]
freq             54
Name: Regional indicator, dtype: object


153
(0, 'Western Europe', ' ')
(1, 'Western Europe', ' ')
(2, 'Western Europe', ' ')
(3, 'Western Europe', ' ')
(4, 'Western Europe', ' ')
(5, 'Western Europe', ' ')
(6, 'Western Europe', ' ')
(7, 'North America and ANZ', ' ', ' ', ' ')
(8, 'Western Europe', ' ')
(9, 'Western Europe', ' ')
(10, 'North America and ANZ', ' ', ' ', ' ')
(11, 'North America and ANZ', ' ', ' ', ' ')
(12, 'Western Europe', ' ')
(13, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(14, 'Latin America and Caribbean', ' ', ' ', ' ')
(15, 'Western Europe', ' ')
(16, 'Western Europe', ' ')
(17, 'North America and ANZ', ' ', ' ', ' ')
(18, 'Central and Eastern Europe', ' ', ' ', ' ')
(19, 'Western Europe', ' ')
(20, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(21, 'Western Europe', ' ')
(22, 'Western Europe', ' ')
(23, 'Latin America and Caribbean', ' ', ' ', ' ')
(24, 'East Asia', ' ')
(25, 'Latin America and Caribbean', ' ', ' ', ' ')
(26, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(27, 'Western Europe', ' ')
(28, 'Latin America and Caribbean', ' ', ' ', ' ')
(29, 'Western Europe', ' ')
(30, 'Southeast Asia', ' ')
(31, 'Latin America and Caribbean', ' ', ' ', ' ')
(32, 'Central and Eastern Europe', ' ', ' ', ' ')
(33, 'Latin America and Caribbean', ' ', ' ', ' ')
(34, 'Central and Eastern Europe', ' ', ' ', ' ')
(35, 'Latin America and Caribbean', ' ', ' ', ' ')
(36, 'Central and Eastern Europe', ' ', ' ', ' ')
(37, 'Commonwealth of Independent States', ' ', ' ', ' ')
(38, 'Latin America and Caribbean', ' ', ' ', ' ')
(39, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(40, 'Central and Eastern Europe', ' ', ' ', ' ')
(41, 'Latin America and Caribbean', ' ', ' ', ' ')
(42, 'Central and Eastern Europe', ' ', ' ', ' ')
(43, 'Latin America and Caribbean', ' ', ' ', ' ')
(44, 'Western Europe', ' ')
(45, 'Latin America and Caribbean', ' ', ' ', ' ')
(46, 'Central and Eastern Europe', ' ', ' ', ' ')
(47, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(48, 'Sub-Saharan Africa', '-', ' ')
(49, 'Commonwealth of Independent States', ' ', ' ', ' ')
(50, 'Central and Eastern Europe', ' ', ' ', ' ')
(51, 'Southeast Asia', ' ')
(52, 'Central and Eastern Europe', ' ', ' ', ' ')
(53, 'Southeast Asia', ' ')
(54, 'Latin America and Caribbean', ' ', ' ', ' ')
(55, 'Latin America and Caribbean', ' ', ' ', ' ')
(56, 'Central and Eastern Europe', ' ', ' ', ' ')
(57, 'Latin America and Caribbean', ' ', ' ', ' ')
(58, 'Western Europe', ' ')
(59, 'Latin America and Caribbean', ' ', ' ', ' ')
(60, 'East Asia', ' ')
(61, 'East Asia', ' ')
(62, 'Latin America and Caribbean', ' ', ' ', ' ')
(63, 'Central and Eastern Europe', ' ', ' ', ' ')
(64, 'Latin America and Caribbean', ' ', ' ', ' ')
(65, 'South Asia', ' ')
(66, 'Latin America and Caribbean', ' ', ' ', ' ')
(67, 'Latin America and Caribbean', ' ', ' ', ' ')
(68, 'Central and Eastern Europe', ' ', ' ', ' ')
(69, 'Commonwealth of Independent States', ' ', ' ', ' ')
(70, 'Commonwealth of Independent States', ' ', ' ', ' ')
(71, 'Central and Eastern Europe', ' ', ' ', ' ')
(72, 'Commonwealth of Independent States', ' ', ' ', ' ')
(73, 'Commonwealth of Independent States', ' ', ' ', ' ')
(74, 'Commonwealth of Independent States', ' ', ' ', ' ')
(75, 'Western Europe', ' ')
(76, 'Western Europe', ' ')
(77, 'East Asia', ' ')
(78, 'Central and Eastern Europe', ' ', ' ', ' ')
(79, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(80, 'East Asia', ' ')
(81, 'Southeast Asia', ' ')
(82, 'Southeast Asia', ' ')
(83, 'Southeast Asia', ' ')
(84, 'Sub-Saharan Africa', '-', ' ')
(85, 'Sub-Saharan Africa', '-', ' ')
(86, 'South Asia', ' ')
(87, 'Sub-Saharan Africa', '-', ' ')
(88, 'Commonwealth of Independent States', ' ', ' ', ' ')
(89, 'Central and Eastern Europe', ' ', ' ', ' ')
(90, 'Sub-Saharan Africa', '-', ' ')
(91, 'South Asia', ' ')
(92, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(93, 'East Asia', ' ')
(94, 'Commonwealth of Independent States', ' ', ' ', ' ')
(95, 'Central and Eastern Europe', ' ', ' ', ' ')
(96, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(97, 'Sub-Saharan Africa', '-', ' ')
(98, 'Latin America and Caribbean', ' ', ' ', ' ')
(99, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(100, 'Sub-Saharan Africa', '-', ' ')
(101, 'Sub-Saharan Africa', '-', ' ')
(102, 'Sub-Saharan Africa', '-', ' ')
(103, 'Southeast Asia', ' ')
(104, 'Central and Eastern Europe', ' ', ' ', ' ')
(105, 'Southeast Asia', ' ')
(106, 'South Asia', ' ')
(107, 'Sub-Saharan Africa', '-', ' ')
(108, 'Sub-Saharan Africa', '-', ' ')
(109, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(110, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(111, 'Sub-Saharan Africa', '-', ' ')
(112, 'Sub-Saharan Africa', '-', ' ')
(113, 'Sub-Saharan Africa', '-', ' ')
(114, 'Sub-Saharan Africa', '-', ' ')
(115, 'Commonwealth of Independent States', ' ', ' ', ' ')
(116, 'Commonwealth of Independent States', ' ', ' ', ' ')
(117, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(118, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(119, 'Sub-Saharan Africa', '-', ' ')
(120, 'Sub-Saharan Africa', '-', ' ')
(121, 'Sub-Saharan Africa', '-', ' ')
(122, 'Commonwealth of Independent States', ' ', ' ', ' ')
(123, 'Sub-Saharan Africa', '-', ' ')
(124, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(125, 'Sub-Saharan Africa', '-', ' ')
(126, 'Sub-Saharan Africa', '-', ' ')
(127, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(128, 'Sub-Saharan Africa', '-', ' ')
(129, 'South Asia', ' ')
(130, 'Sub-Saharan Africa', '-', ' ')
(131, 'Sub-Saharan Africa', '-', ' ')
(132, 'Southeast Asia', ' ')
(133, 'Sub-Saharan Africa', '-', ' ')
(134, 'Sub-Saharan Africa', '-', ' ')
(135, 'Sub-Saharan Africa', '-', ' ')
(136, 'Sub-Saharan Africa', '-', ' ')
(137, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(138, 'Sub-Saharan Africa', '-', ' ')
(139, 'Sub-Saharan Africa', '-', ' ')
(140, 'Sub-Saharan Africa', '-', ' ')
(141, 'Latin America and Caribbean', ' ', ' ', ' ')
(142, 'Sub-Saharan Africa', '-', ' ')
(143, 'South Asia', ' ')
(144, 'Sub-Saharan Africa', '-', ' ')
(145, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(146, 'Sub-Saharan Africa', '-', ' ')
(147, 'Sub-Saharan Africa', '-', ' ')
(148, 'Sub-Saharan Africa', '-', ' ')
(149, 'Sub-Saharan Africa', '-', ' ')
(150, 'Sub-Saharan Africa', '-', ' ')
(151, 'Sub-Saharan Africa', '-', ' ')
(152, 'South Asia', ' ')

In [28]:
# Presenting the unique values in the region column, to identify necessary changes.
list(data_table[region_column_name].unique())

['Western Europe',
 'North America and ANZ',
 'Middle East and North Africa',
 'Latin America and Caribbean',
 'Central and Eastern Europe',
 'East Asia',
 'Southeast Asia',
 'Commonwealth of Independent States',
 'Sub-Saharan Africa',
 'South Asia']

In [29]:
# Checking and presenting which non-alphabetic characters are contained among the values and
# the respective values to identify possible changes.
for i in range(len(values)):
    if len(values[i]) > 2:
        found = False
        for j in range(2, len(values[i])):
            if values[i][j] != " ":
                found = True
                break
        if found:
            value = str(values[i][0]) + " -- "
            value += values[i][1] + " -- "
            for j in range(2, len(values[i])):
                if values[i][j] != " ":
                    value += values[i][j] + " -- "
            value = value[0:-4]
            print(value)

48 -- Sub-Saharan Africa -- -
84 -- Sub-Saharan Africa -- -
85 -- Sub-Saharan Africa -- -
87 -- Sub-Saharan Africa -- -
90 -- Sub-Saharan Africa -- -
97 -- Sub-Saharan Africa -- -
100 -- Sub-Saharan Africa -- -
101 -- Sub-Saharan Africa -- -
102 -- Sub-Saharan Africa -- -
107 -- Sub-Saharan Africa -- -
108 -- Sub-Saharan Africa -- -
111 -- Sub-Saharan Africa -- -
112 -- Sub-Saharan Africa -- -
113 -- Sub-Saharan Africa -- -
114 -- Sub-Saharan Africa -- -
119 -- Sub-Saharan Africa -- -
120 -- Sub-Saharan Africa -- -
121 -- Sub-Saharan Africa -- -
123 -- Sub-Saharan Africa -- -
125 -- Sub-Saharan Africa -- -
126 -- Sub-Saharan Africa -- -
128 -- Sub-Saharan Africa -- -
130 -- Sub-Saharan Africa -- -
131 -- Sub-Saharan Africa -- -
133 -- Sub-Saharan Africa -- -
134 -- Sub-Saharan Africa -- -
135 -- Sub-Saharan Africa -- -
136 -- Sub-Saharan Africa -- -
138 -- Sub-Saharan Africa -- -
139 -- Sub-Saharan Africa -- -
140 -- Sub-Saharan Africa -- -
142 -- Sub-Saharan Africa -- -
144 -- Sub-Saharan Africa -- -
146 -- Sub-Saharan Africa -- -
147 -- Sub-Saharan Africa -- -
148 -- Sub-Saharan Africa -- -
149 -- Sub-Saharan Africa -- -
150 -- Sub-Saharan Africa -- -
151 -- Sub-Saharan Africa -- -

In [30]:
# Storing country and region data of year 2020 in the result data structure.
table_results = include_data_table_results(data_table=data_table,
                                           result_columns=result_columns,
                                           country_column_name=country_column_name,
                                           region_column_name=region_column_name,
                                           table_results=table_results)

                      COUNTRY              REGION
0                     Finland
1                     Denmark
2                     Iceland
3                      Israel
4                 Netherlands
..                        ...                 ...
581  Central African Republic  Sub-Saharan Africa
582                    Rwanda  Sub-Saharan Africa
583                  Zimbabwe  Sub-Saharan Africa
584               South Sudan  Sub-Saharan Africa
585               Afghanistan          South Asia

[586 rows x 2 columns]

In [31]:
# Collecting information to read the data file referring to the first year considered in the analysis (2019).
year_input_file = 4
input_file = path_original_data + str(years_analysis[year_input_file]) + "/" + info_read_input_files[year_input_file][0]
sheet_input_file = info_read_input_files[year_input_file][1]
line_header_input_file = info_read_input_files[year_input_file][2]

# Reading the data file referring to the first year considered in the analysis (2019).
data_table = pd.read_excel(io=input_file,
                           sheet_name=sheet_input_file,
                           header=line_header_input_file)

# Presenting the names and types of the columns of the data referring to the first year considered in the analysis (2019).
print(data_table.columns)
print(data_table.dtypes)

Index(['Country', 'Happiness score', 'Whisker-high', 'Whisker-low',
       'Dystopia (1.88) + residual', 'Explained by: GDP per capita',
       'Explained by: Social support', 'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption'],
      dtype='object')
Country                                        object
Happiness score                               float64
Whisker-high                                  float64
Whisker-low                                   float64
Dystopia (1.88) + residual                    float64
Explained by: GDP per capita                  float64
Explained by: Social support                  float64
Explained by: Healthy life expectancy         float64
Explained by: Freedom to make life choices    float64
Explained by: Generosity                      float64
Explained by: Perceptions of corruption       float64
dtype: object

In [32]:
# Storing the column names referring to the countries and regions data in the dataset for the year 2019.
country_column_name = "Country"
region_column_name = ""

In [33]:
# Collecting, storing and presenting the values in the country column that contain non-alphabetic characters,
# referring to the data of year 2019.
values = find_present_non_word_values(data_table=data_table, column_name=country_column_name)

['Finland' 'Denmark' 'Norway' 'Iceland' 'Netherlands' 'Switzerland'
 'Sweden' 'New Zealand' 'Canada' 'Austria' 'Australia' 'Costa Rica'
 'Israel' 'Luxembourg' 'United Kingdom' 'Ireland' 'Germany' 'Belgium'
 'United States' 'Czech Republic' 'United Arab Emirates' 'Malta' 'Mexico'
 'France' 'Taiwan Province of China' 'Chile' 'Guatemala' 'Saudi Arabia'
 'Qatar' 'Spain' 'Panama' 'Brazil' 'Uruguay' 'Singapore' 'El Salvador'
 'Italy' 'Bahrain' 'Slovakia' 'Trinidad and Tobago' 'Poland' 'Uzbekistan'
 'Lithuania' 'Colombia' 'Slovenia' 'Nicaragua' 'Kosovo' 'Argentina'
 'Romania' 'Cyprus' 'Ecuador' 'Kuwait' 'Thailand' 'Latvia' 'South Korea'
 'Estonia' 'Jamaica' 'Mauritius' 'Japan' 'Honduras' 'Kazakhstan' 'Bolivia'
 'Hungary' 'Paraguay' 'North Cyprus' 'Peru' 'Portugal' 'Pakistan' 'Russia'
 'Philippines' 'Serbia' 'Moldova' 'Libya' 'Montenegro' 'Tajikistan'
 'Croatia' 'Hong Kong S.A.R. of China' 'Dominican Republic'
 'Bosnia and Herzegovina' 'Turkey' 'Malaysia' 'Belarus' 'Greece'
 'Mongolia' 'Macedonia' 'Nigeria' 'Kyrgyzstan' 'Turkmenistan' 'Algeria'
 'Morocco' 'Azerbaijan' 'Lebanon' 'Indonesia' 'China' 'Vietnam' 'Bhutan'
 'Cameroon' 'Bulgaria' 'Ghana' 'Ivory Coast' 'Nepal' 'Jordan' 'Benin'
 'Congo (Brazzaville)' 'Gabon' 'Laos' 'South Africa' 'Albania' 'Venezuela'
 'Cambodia' 'Palestinian Territories' 'Senegal' 'Somalia' 'Namibia'
 'Niger' 'Burkina Faso' 'Armenia' 'Iran' 'Guinea' 'Georgia' 'Gambia'
 'Kenya' 'Mauritania' 'Mozambique' 'Tunisia' 'Bangladesh' 'Iraq'
 'Congo (Kinshasa)' 'Mali' 'Sierra Leone' 'Sri Lanka' 'Myanmar' 'Chad'
 'Ukraine' 'Ethiopia' 'Swaziland' 'Uganda' 'Egypt' 'Zambia' 'Togo' 'India'
 'Liberia' 'Comoros' 'Madagascar' 'Lesotho' 'Burundi' 'Zimbabwe' 'Haiti'
 'Botswana' 'Syria' 'Malawi' 'Yemen' 'Rwanda' 'Tanzania' 'Afghanistan'
 'Central African Republic' 'South Sudan']
156


156
RangeIndex(start=0, stop=156, step=1)
count     156
unique      6
top        []
freq      131
Name: Country, dtype: object


25
(7, 'New Zealand', ' ')
(11, 'Costa Rica', ' ')
(14, 'United Kingdom', ' ')
(18, 'United States', ' ')
(19, 'Czech Republic', ' ')
(20, 'United Arab Emirates', ' ', ' ')
(24, 'Taiwan Province of China', ' ', ' ', ' ')
(27, 'Saudi Arabia', ' ')
(34, 'El Salvador', ' ')
(38, 'Trinidad and Tobago', ' ', ' ')
(53, 'South Korea', ' ')
(63, 'North Cyprus', ' ')
(75, 'Hong Kong S.A.R. of China', ' ', ' ', '.', '.', '. ', ' ')
(76, 'Dominican Republic', ' ')
(77, 'Bosnia and Herzegovina', ' ', ' ')
(98, 'Ivory Coast', ' ')
(102, 'Congo (Brazzaville)', ' (', ')')
(105, 'South Africa', ' ')
(109, 'Palestinian Territories', ' ')
(114, 'Burkina Faso', ' ')
(126, 'Congo (Kinshasa)', ' (', ')')
(128, 'Sierra Leone', ' ')
(129, 'Sri Lanka', ' ')
(154, 'Central African Republic', ' ', ' ')
(155, 'South Sudan', ' ')

In [34]:
# Collecting, storing and presenting the values in the region column that contain non-alphabetic characters,
# referring to the data of year 2019.
values = find_present_non_word_values(data_table=data_table, column_name=region_column_name)

In [35]:
# Storing country and region data of year 2019 in the result data structure.
table_results = include_data_table_results(data_table=data_table,
                                           result_columns=result_columns,
                                           country_column_name=country_column_name,
                                           region_column_name=region_column_name,
                                           table_results=table_results)

                      COUNTRY REGION
0                     Finland
1                     Denmark
2                     Iceland
3                      Israel
4                 Netherlands
..                        ...    ...
737                    Rwanda
738                  Tanzania
739               Afghanistan
740  Central African Republic
741               South Sudan

[742 rows x 2 columns]

In [36]:
# Collecting information to read the data file referring to the first year considered in the analysis (2018).
year_input_file = 5
input_file = path_original_data + str(years_analysis[year_input_file]) + "/" + info_read_input_files[year_input_file][0]
sheet_input_file = info_read_input_files[year_input_file][1]
line_header_input_file = info_read_input_files[year_input_file][2]

# Reading the data file referring to the first year considered in the analysis (2018).
data_table = pd.read_excel(io=input_file,
                           sheet_name=sheet_input_file,
                           header=line_header_input_file)

# Presenting the names and types of the columns of the data referring to the first year considered in the analysis (2018).
print(data_table.columns)
print(data_table.dtypes)

Index(['Country', 'Happiness score', 'Whisker-high', 'Whisker-low',
       'Dystopia (1.92) + residual', 'Explained by: GDP per capita',
       'Explained by: Social support', 'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14',
       'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18',
       'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')
Country                                        object
Happiness score                               float64
Whisker-high                                  float64
Whisker-low                                   float64
Dystopia (1.92) + residual                    float64
Explained by: GDP per capita                  float64
Explained by: Social support                  float64
Explained by: Healthy life expectancy         float64
Explained by: Freedom to make life choices    float64
Explained by: Generosity                      float64
Explained by: Perceptions of corruption       float64
Unnamed: 11                                   float64
Unnamed: 12                                   float64
Unnamed: 13                                   float64
Unnamed: 14                                   float64
Unnamed: 15                                   float64
Unnamed: 16                                   float64
Unnamed: 17                                   float64
Unnamed: 18                                   float64
Unnamed: 19                                   float64
Unnamed: 20                                   float64
Unnamed: 21                                   float64
Unnamed: 22                                   float64
Unnamed: 23                                    object
dtype: object

In [37]:
# Storing the column names referring to the countries and regions data in the dataset for the year 2018.
country_column_name = "Country"
region_column_name = ""

In [38]:
# Collecting, storing and presenting the values in the country column that contain non-alphabetic characters,
# referring to the data of year 2018.
values = find_present_non_word_values(data_table=data_table, column_name=country_column_name)

['Finland' 'Norway' 'Denmark' 'Iceland' 'Switzerland' 'Netherlands'
 'Canada' 'New Zealand' 'Sweden' 'Australia' 'Israel' 'Austria'
 'Costa Rica' 'Ireland' 'Germany' 'Belgium' 'Luxembourg' 'United States'
 'United Kingdom' 'United Arab Emirates' 'Czech Republic' 'Malta' 'France'
 'Mexico' 'Chile' 'Taiwan Province of China' 'Panama' 'Brazil' 'Argentina'
 'Guatemala' 'Uruguay' 'Qatar' 'Saudi Arabia' 'Singapore' 'Malaysia'
 'Spain' 'Colombia' 'Trinidad & Tobago' 'Slovakia' 'El Salvador'
 'Nicaragua' 'Poland' 'Bahrain' 'Uzbekistan' 'Kuwait' 'Thailand' 'Italy'
 'Ecuador' 'Belize' 'Lithuania' 'Slovenia' 'Romania' 'Latvia' 'Japan'
 'Mauritius' 'Jamaica' 'South Korea' 'Northern Cyprus' 'Russia'
 'Kazakhstan' 'Cyprus' 'Bolivia' 'Estonia' 'Paraguay' 'Peru' 'Kosovo'
 'Moldova' 'Turkmenistan' 'Hungary' 'Libya' 'Philippines' 'Honduras'
 'Belarus' 'Turkey' 'Pakistan' 'Hong Kong SAR, China' 'Portugal' 'Serbia'
 'Greece' 'Tajikistan' 'Montenegro' 'Croatia' 'Dominican Republic'
 'Algeria' 'Morocco' 'China' 'Azerbaijan' 'Lebanon' 'Macedonia' 'Jordan'
 'Nigeria' 'Kyrgyzstan' 'Bosnia and Herzegovina' 'Mongolia' 'Vietnam'
 'Indonesia' 'Bhutan' 'Somalia' 'Cameroon' 'Bulgaria' 'Nepal' 'Venezuela'
 'Gabon' 'Palestinian Territories' 'South Africa' 'Iran' 'Ivory Coast'
 'Ghana' 'Senegal' 'Laos' 'Tunisia' 'Albania' 'Sierra Leone'
 'Congo (Brazzaville)' 'Bangladesh' 'Sri Lanka' 'Iraq' 'Mali' 'Namibia'
 'Cambodia' 'Burkina Faso' 'Egypt' 'Mozambique' 'Kenya' 'Zambia'
 'Mauritania' 'Ethiopia' 'Georgia' 'Armenia' 'Myanmar' 'Chad'
 'Congo (Kinshasa)' 'India' 'Niger' 'Uganda' 'Benin' 'Sudan' 'Ukraine'
 'Togo' 'Guinea' 'Lesotho' 'Angola' 'Madagascar' 'Zimbabwe' 'Afghanistan'
 'Botswana' 'Malawi' 'Haiti' 'Liberia' 'Syria' 'Rwanda' 'Yemen' 'Tanzania'
 'South Sudan' 'Central African Republic' 'Burundi' nan]
157


157
RangeIndex(start=0, stop=157, step=1)
count     157
unique      7
top        []
freq      132
Name: Country, dtype: object


25
(7, 'New Zealand', ' ')
(12, 'Costa Rica', ' ')
(17, 'United States', ' ')
(18, 'United Kingdom', ' ')
(19, 'United Arab Emirates', ' ', ' ')
(20, 'Czech Republic', ' ')
(25, 'Taiwan Province of China', ' ', ' ', ' ')
(32, 'Saudi Arabia', ' ')
(37, 'Trinidad & Tobago', ' & ')
(39, 'El Salvador', ' ')
(56, 'South Korea', ' ')
(57, 'Northern Cyprus', ' ')
(75, 'Hong Kong SAR, China', ' ', ' ', ', ')
(82, 'Dominican Republic', ' ')
(92, 'Bosnia and Herzegovina', ' ', ' ')
(103, 'Palestinian Territories', ' ')
(104, 'South Africa', ' ')
(106, 'Ivory Coast', ' ')
(112, 'Sierra Leone', ' ')
(113, 'Congo (Brazzaville)', ' (', ')')
(115, 'Sri Lanka', ' ')
(120, 'Burkina Faso', ' ')
(131, 'Congo (Kinshasa)', ' (', ')')
(153, 'South Sudan', ' ')
(154, 'Central African Republic', ' ', ' ')

In [39]:
# Changing the values for country data referring to the year 2018 that contain non-alphabetic characters,
# in the result data structure.
indices_to_change = []
new_values = []

# For the year 2018, only two values will be changed.
indices_to_change = [37, 75]
new_values = ["Trinidad and Tobago", "Hong Kong S.A.R. of China"]

# Presenting the values to be changed.
print(indices_to_change)
print(new_values)
print(len(indices_to_change))
print(len(new_values))

# Changing the identifies values in the result data structure.
for i in range(len(indices_to_change)):
    data_table.loc[indices_to_change[i], country_column_name] = new_values[i]

# Presenting the new values in the result data structure.
print(data_table[country_column_name][indices_to_change])

[37, 75]
['Trinidad and Tobago', 'Hong Kong S.A.R. of China']
2
2
37          Trinidad and Tobago
75    Hong Kong S.A.R. of China
Name: Country, dtype: object

In [40]:
# Collecting, storing and presenting the values in the region column that contain non-alphabetic characters,
# referring to the data of year 2018.
values = find_present_non_word_values(data_table=data_table, column_name=region_column_name)

In [41]:
# Storing country and region data of year 2018 in the result data structure.
table_results = include_data_table_results(data_table=data_table,
                                           result_columns=result_columns,
                                           country_column_name=country_column_name,
                                           region_column_name=region_column_name,
                                           table_results=table_results)

                      COUNTRY REGION
0                     Finland
1                     Denmark
2                     Iceland
3                      Israel
4                 Netherlands
..                        ...    ...
894                  Tanzania
895               South Sudan
896  Central African Republic
897                   Burundi
898                       NaN

[899 rows x 2 columns]

In [42]:
# Collecting information to read the data file referring to the first year considered in the analysis (2017).
year_input_file = 6
input_file = path_original_data + str(years_analysis[year_input_file]) + "/" + info_read_input_files[year_input_file][0]
sheet_input_file = info_read_input_files[year_input_file][1]
line_header_input_file = info_read_input_files[year_input_file][2]

# Reading the data file referring to the first year considered in the analysis (2017).
data_table = pd.read_excel(io=input_file,
                           sheet_name=sheet_input_file,
                           header=line_header_input_file)

# Presenting the names and types of the columns of the data referring to the first year considered in the analysis (2017).
print(data_table.columns)
print(data_table.dtypes)

Index(['Country', 'Happiness score', 'Whisker-high', 'Whisker-low',
       'Explained by: GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia (1.85) + residual'],
      dtype='object')
Country                                        object
Happiness score                               float64
Whisker-high                                  float64
Whisker-low                                   float64
Explained by: GDP per capita                  float64
Explained by: Social support                  float64
Explained by: Healthy life expectancy         float64
Explained by: Freedom to make life choices    float64
Explained by: Generosity                      float64
Explained by: Perceptions of corruption       float64
Dystopia (1.85) + residual                    float64
dtype: object

In [43]:
# Storing the column names referring to the countries and regions data in the dataset for the year 2017.
country_column_name = "Country"
region_column_name = ""

In [44]:
# Collecting, storing and presenting the values in the country column that contain non-alphabetic characters,
# referring to the data of year 2017.
values = find_present_non_word_values(data_table=data_table, column_name=country_column_name)

['Norway' 'Denmark' 'Iceland' 'Switzerland' 'Finland' 'Netherlands'
 'Canada' 'New Zealand' 'Sweden' 'Australia' 'Israel' 'Costa Rica'
 'Austria' 'United States' 'Ireland' 'Germany' 'Belgium' 'Luxembourg'
 'United Kingdom' 'Chile' 'United Arab Emirates' 'Brazil' 'Czech Republic'
 'Argentina' 'Mexico' 'Singapore' 'Malta' 'Uruguay' 'Guatemala' 'Panama'
 'France' 'Thailand' 'Taiwan Province of China' 'Spain' 'Qatar' 'Colombia'
 'Saudi Arabia' 'Trinidad and Tobago' 'Kuwait' 'Slovakia' 'Bahrain'
 'Malaysia' 'Nicaragua' 'Ecuador' 'El Salvador' 'Poland' 'Uzbekistan'
 'Italy' 'Russia' 'Belize' 'Japan' 'Lithuania' 'Algeria' 'Latvia'
 'South Korea' 'Moldova' 'Romania' 'Bolivia' 'Turkmenistan' 'Kazakhstan'
 'North Cyprus' 'Slovenia' 'Peru' 'Mauritius' 'Cyprus' 'Estonia' 'Belarus'
 'Libya' 'Turkey' 'Paraguay' 'Hong Kong S.A.R., China' 'Philippines'
 'Serbia' 'Jordan' 'Hungary' 'Jamaica' 'Croatia' 'Kosovo' 'China'
 'Pakistan' 'Indonesia' 'Venezuela' 'Montenegro' 'Morocco' 'Azerbaijan'
 'Dominican Republic' 'Greece' 'Lebanon' 'Portugal'
 'Bosnia and Herzegovina' 'Honduras' 'Macedonia' 'Somalia' 'Vietnam'
 'Nigeria' 'Tajikistan' 'Bhutan' 'Kyrgyzstan' 'Nepal' 'Mongolia'
 'South Africa' 'Tunisia' 'Palestinian Territories' 'Egypt' 'Bulgaria'
 'Sierra Leone' 'Cameroon' 'Iran' 'Albania' 'Bangladesh' 'Namibia' 'Kenya'
 'Mozambique' 'Myanmar' 'Senegal' 'Zambia' 'Iraq' 'Gabon' 'Ethiopia'
 'Sri Lanka' 'Armenia' 'India' 'Mauritania' 'Congo (Brazzaville)'
 'Georgia' 'Congo (Kinshasa)' 'Mali' 'Ivory Coast' 'Cambodia' 'Sudan'
 'Ghana' 'Ukraine' 'Uganda' 'Burkina Faso' 'Niger' 'Malawi' 'Chad'
 'Zimbabwe' 'Lesotho' 'Angola' 'Afghanistan' 'Botswana' 'Benin'
 'Madagascar' 'Haiti' 'Yemen' 'South Sudan' 'Liberia' 'Guinea' 'Togo'
 'Rwanda' 'Syria' 'Tanzania' 'Burundi' 'Central African Republic']
155


155
RangeIndex(start=0, stop=155, step=1)
count     155
unique      6
top        []
freq      130
Name: Country, dtype: object


25
(7, 'New Zealand', ' ')
(11, 'Costa Rica', ' ')
(13, 'United States', ' ')
(18, 'United Kingdom', ' ')
(20, 'United Arab Emirates', ' ', ' ')
(22, 'Czech Republic', ' ')
(32, 'Taiwan Province of China', ' ', ' ', ' ')
(36, 'Saudi Arabia', ' ')
(37, 'Trinidad and Tobago', ' ', ' ')
(44, 'El Salvador', ' ')
(54, 'South Korea', ' ')
(60, 'North Cyprus', ' ')
(70, 'Hong Kong S.A.R., China', ' ', ' ', '.', '.', '., ')
(85, 'Dominican Republic', ' ')
(89, 'Bosnia and Herzegovina', ' ', ' ')
(100, 'South Africa', ' ')
(102, 'Palestinian Territories', ' ')
(105, 'Sierra Leone', ' ')
(119, 'Sri Lanka', ' ')
(123, 'Congo (Brazzaville)', ' (', ')')
(125, 'Congo (Kinshasa)', ' (', ')')
(127, 'Ivory Coast', ' ')
(133, 'Burkina Faso', ' ')
(146, 'South Sudan', ' ')
(154, 'Central African Republic', ' ', ' ')

In [45]:
# Changing the values for country data referring to the year 2017 that contain non-alphabetic characters,
# in the result data structure.
indices_to_change = []
new_values = []

# For the year 2017, only one value will be changed.
indices_to_change = [70]
new_values = ["Hong Kong S.A.R. of China"]

# Presenting the values to be changed.
print(indices_to_change)
print(new_values)
print(len(indices_to_change))
print(len(new_values))

# Changing the identifies values in the result data structure.
for i in range(len(indices_to_change)):
    data_table.loc[indices_to_change[i], country_column_name] = new_values[i]

# Presenting the new values in the result data structure.
print(data_table[country_column_name][indices_to_change])

[70]
['Hong Kong S.A.R. of China']
1
1
70    Hong Kong S.A.R. of China
Name: Country, dtype: object

In [46]:
# Collecting, storing and presenting the values in the region column that contain non-alphabetic characters,
# referring to the data of year 2017.
values = find_present_non_word_values(data_table=data_table, column_name=region_column_name)

In [47]:
# Storing country and region data of year 2017 in the result data structure.
table_results = include_data_table_results(data_table=data_table,
                                           result_columns=result_columns,
                                           country_column_name=country_column_name,
                                           region_column_name=region_column_name,
                                           table_results=table_results)

                       COUNTRY REGION
0                      Finland
1                      Denmark
2                      Iceland
3                       Israel
4                  Netherlands
...                        ...    ...
1049                    Rwanda
1050                     Syria
1051                  Tanzania
1052                   Burundi
1053  Central African Republic

[1054 rows x 2 columns]

In [48]:
# Collecting information to read the data file referring to the first year considered in the analysis (2016).
year_input_file = 7
input_file = path_original_data + str(years_analysis[year_input_file]) + "/" + info_read_input_files[year_input_file][0]
sheet_input_file = info_read_input_files[year_input_file][1]
line_header_input_file = info_read_input_files[year_input_file][2]

# Reading the data file referring to the first year considered in the analysis (2016).
data_table = pd.read_excel(io=input_file,
                           sheet_name=sheet_input_file,
                           header=line_header_input_file)

# Presenting the names and types of the columns of the data referring to the first year considered in the analysis (2016).
print(data_table.columns)
print(data_table.dtypes)

Index(['Country', 'Happiness score', 'Whisker-high', 'Whisker-low',
       'Explained by: GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia (2.33) + residual', 'Unnamed: 11', 'Unnamed: 12',
       'Figure 2.2: Ranking of Happiness 2013-2015'],
      dtype='object')
Country                                        object
Happiness score                               float64
Whisker-high                                  float64
Whisker-low                                   float64
Explained by: GDP per capita                  float64
Explained by: Social support                  float64
Explained by: Healthy life expectancy         float64
Explained by: Freedom to make life choices    float64
Explained by: Generosity                      float64
Explained by: Perceptions of corruption       float64
Dystopia (2.33) + residual                    float64
Unnamed: 11                                   float64
Unnamed: 12                                   float64
Figure 2.2: Ranking of Happiness 2013-2015    float64
dtype: object

In [49]:
# Storing the column names referring to the countries and regions data in the dataset for the year 2016.
country_column_name = "Country"
region_column_name = ""

In [50]:
# Collecting, storing and presenting the values in the country column that contain non-alphabetic characters,
# referring to the data of year 2016.
values = find_present_non_word_values(data_table=data_table, column_name=country_column_name)

['Denmark' 'Switzerland' 'Iceland' 'Norway' 'Finland' 'Canada'
 'Netherlands' 'New Zealand' 'Australia' 'Sweden' 'Israel' 'Austria'
 'United States' 'Costa Rica' 'Puerto Rico' 'Germany' 'Brazil' 'Belgium'
 'Ireland' 'Luxembourg' 'Mexico' 'Singapore' 'United Kingdom' 'Chile'
 'Panama' 'Argentina' 'Czech Republic' 'United Arab Emirates' 'Uruguay'
 'Malta' 'Colombia' 'France' 'Thailand' 'Saudi Arabia' 'Taiwan' 'Qatar'
 'Spain' 'Algeria' 'Guatemala' 'Suriname' 'Kuwait' 'Bahrain'
 'Trinidad and Tobago' 'Venezuela' 'Slovakia' 'El Salvador' 'Malaysia'
 'Nicaragua' 'Uzbekistan' 'Italy' 'Ecuador' 'Belize' 'Japan' 'Kazakhstan'
 'Moldova' 'Russia' 'Poland' 'South Korea' 'Bolivia' 'Lithuania' 'Belarus'
 'North Cyprus' 'Slovenia' 'Peru' 'Turkmenistan' 'Mauritius' 'Libya'
 'Latvia' 'Cyprus' 'Paraguay' 'Romania' 'Estonia' 'Jamaica' 'Croatia'
 'Hong Kong' 'Somalia' 'Kosovo' 'Turkey' 'Indonesia' 'Jordan' 'Azerbaijan'
 'Philippines' 'China' 'Bhutan' 'Kyrgyzstan' 'Serbia'
 'Bosnia and Herzegovina' 'Montenegro' 'Dominican Republic' 'Morocco'
 'Hungary' 'Pakistan' 'Lebanon' 'Portugal' 'Macedonia' 'Vietnam'
 'Somaliland region' 'Tunisia' 'Greece' 'Tajikistan' 'Mongolia' 'Laos'
 'Nigeria' 'Honduras' 'Iran' 'Zambia' 'Nepal' 'Palestinian Territories'
 'Albania' 'Bangladesh' 'Sierra Leone' 'Iraq' 'Namibia' 'Cameroon'
 'Ethiopia' 'South Africa' 'Sri Lanka' 'India' 'Myanmar' 'Egypt' 'Armenia'
 'Kenya' 'Ukraine' 'Ghana' 'Congo (Kinshasa)' 'Georgia'
 'Congo (Brazzaville)' 'Senegal' 'Bulgaria' 'Mauritania' 'Zimbabwe'
 'Malawi' 'Sudan' 'Gabon' 'Mali' 'Haiti' 'Botswana' 'Comoros'
 'Ivory Coast' 'Cambodia' 'Angola' 'Niger' 'South Sudan' 'Chad'
 'Burkina Faso' 'Uganda' 'Yemen' 'Madagascar' 'Tanzania' 'Liberia'
 'Guinea' 'Rwanda' 'Benin' 'Afghanistan' 'Togo' 'Syria' 'Burundi']
157


157
RangeIndex(start=0, stop=157, step=1)
count     157
unique      4
top        []
freq      132
Name: Country, dtype: object


25
(7, 'New Zealand', ' ')
(12, 'United States', ' ')
(13, 'Costa Rica', ' ')
(14, 'Puerto Rico', ' ')
(22, 'United Kingdom', ' ')
(26, 'Czech Republic', ' ')
(27, 'United Arab Emirates', ' ', ' ')
(33, 'Saudi Arabia', ' ')
(42, 'Trinidad and Tobago', ' ', ' ')
(45, 'El Salvador', ' ')
(57, 'South Korea', ' ')
(61, 'North Cyprus', ' ')
(74, 'Hong Kong', ' ')
(86, 'Bosnia and Herzegovina', ' ', ' ')
(88, 'Dominican Republic', ' ')
(96, 'Somaliland region', ' ')
(107, 'Palestinian Territories', ' ')
(110, 'Sierra Leone', ' ')
(115, 'South Africa', ' ')
(116, 'Sri Lanka', ' ')
(124, 'Congo (Kinshasa)', ' (', ')')
(126, 'Congo (Brazzaville)', ' (', ')')
(138, 'Ivory Coast', ' ')
(142, 'South Sudan', ' ')
(144, 'Burkina Faso', ' ')

In [51]:
# Collecting, storing and presenting the values in the region column that contain non-alphabetic characters,
# referring to the data of year 2016.
values = find_present_non_word_values(data_table=data_table, column_name=region_column_name)

In [52]:
# Storing country and region data of year 2016 in the result data structure.
table_results = include_data_table_results(data_table=data_table,
                                           result_columns=result_columns,
                                           country_column_name=country_column_name,
                                           region_column_name=region_column_name,
                                           table_results=table_results)

          COUNTRY REGION
0         Finland
1         Denmark
2         Iceland
3          Israel
4     Netherlands
...           ...    ...
1206        Benin
1207  Afghanistan
1208         Togo
1209        Syria
1210      Burundi

[1211 rows x 2 columns]

In [53]:
# Collecting information to read the data file referring to the first year considered in the analysis (2015).
year_input_file = 8
input_file = path_original_data + str(years_analysis[year_input_file]) + "/" + info_read_input_files[year_input_file][0]
sheet_input_file = info_read_input_files[year_input_file][1]
line_header_input_file = info_read_input_files[year_input_file][2]

# Reading the data file referring to the first year considered in the analysis (2015).
data_table = pd.read_excel(io=input_file,
                           sheet_name=sheet_input_file,
                           header=line_header_input_file)

# Presenting the names and types of the columns of the data referring to the first year considered in the analysis (2015).
print(data_table.columns)
print(data_table.dtypes)

Index(['WP5 Country', 'country', 'Regional indicator', 'Ladder score',
       'Standard error of ladder score', 'Logged GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Dystopia + residual', 'Explained by: Log GDP per capita',
       'Explained by: Social support', 'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Trust in national government', 'Democratic Quality 2012',
       'Delivery Quality 2012',
       'Most people can be trusted, Gallup, mostly 2009-10',
       'Most people can be trusted, WVS round 1981-1984',
       'Most people can be trusted, WVS round 1989-1993',
       'Most people can be trusted, WVS round 1994-1998',
       'Most people can be trusted, WVS round 1999-2004',
       'Most people can be trusted, WVS round 2005-2009',
       'Most people can be trusted, WVS round 2010-2014'],
      dtype='object')
WP5 Country                                            object
country                                                object
Regional indicator                                     object
Ladder score                                          float64
Standard error of ladder score                        float64
Logged GDP per capita                                 float64
Social support                                        float64
Healthy life expectancy                               float64
Freedom to make life choices                          float64
Generosity                                            float64
Perceptions of corruption                             float64
Ladder score in Dystopia                              float64
Dystopia + residual                                   float64
Explained by: Log GDP per capita                      float64
Explained by: Social support                          float64
Explained by: Healthy life expectancy                 float64
Explained by: Freedom to make life choices            float64
Explained by: Generosity                              float64
Explained by: Perceptions of corruption               float64
Trust in national government                          float64
Democratic Quality 2012                               float64
Delivery Quality 2012                                 float64
Most people can be trusted, Gallup, mostly 2009-10    float64
Most people can be trusted, WVS round 1981-1984       float64
Most people can be trusted, WVS round 1989-1993       float64
Most people can be trusted, WVS round 1994-1998       float64
Most people can be trusted, WVS round 1999-2004       float64
Most people can be trusted, WVS round 2005-2009       float64
Most people can be trusted, WVS round 2010-2014       float64
dtype: object

In [54]:
# Storing the column names referring to the countries and regions data in the dataset for the year 2015.
country_column_name = "country"
region_column_name = "Regional indicator"

In [55]:
# Collecting, storing and presenting the values in the country column that contain non-alphabetic characters,
# referring to the data of year 2015.
values = find_present_non_word_values(data_table=data_table, column_name=country_column_name)

['Switzerland' 'Iceland' 'Denmark' 'Norway' 'Canada' 'Finland'
 'Netherlands' 'Sweden' 'New Zealand' 'Australia' 'Israel' 'Costa Rica'
 'Austria' 'Mexico' 'United States' 'Brazil' 'Luxembourg' 'Ireland'
 'Belgium' 'United Arab Emirates' 'United Kingdom' 'Oman' 'Venezuela'
 'Singapore' 'Panama' 'Germany' 'Chile' 'Qatar' 'France' 'Argentina'
 'Czech Republic' 'Uruguay' 'Colombia' 'Thailand' 'Saudi Arabia' 'Spain'
 'Malta' 'Taiwan' 'Kuwait' 'Suriname' 'Trinidad and Tobago' 'El Salvador'
 'Guatemala' 'Uzbekistan' 'Slovakia' 'Japan' 'South Korea' 'Ecuador'
 'Bahrain' 'Italy' 'Bolivia' 'Moldova' 'Paraguay' 'Kazakhstan' 'Slovenia'
 'Lithuania' 'Nicaragua' 'Peru' 'Belarus' 'Poland' 'Malaysia' 'Croatia'
 'Libya' 'Russia' 'Jamaica' 'North Cyprus' 'Cyprus' 'Algeria' 'Kosovo'
 'Turkmenistan' 'Mauritius' 'Hong Kong' 'Estonia' 'Indonesia' 'Vietnam'
 'Turkey' 'Kyrgyzstan' 'Nigeria' 'Bhutan' 'Azerbaijan' 'Pakistan' 'Jordan'
 'Montenegro' 'China' 'Zambia' 'Romania' 'Serbia' 'Portugal' 'Latvia'
 'Philippines' 'Somaliland region' 'Morocco' 'Macedonia' 'Mozambique'
 'Albania' 'Bosnia and Herzegovina' 'Lesotho' 'Dominican Republic' 'Laos'
 'Mongolia' 'Swaziland' 'Greece' 'Lebanon' 'Hungary' 'Honduras'
 'Tajikistan' 'Tunisia' 'Palestinian Territories' 'Bangladesh' 'Iran'
 'Ukraine' 'Iraq' 'South Africa' 'Ghana' 'Zimbabwe' 'Liberia' 'India'
 'Sudan' 'Haiti' 'Congo (Kinshasa)' 'Nepal' 'Ethiopia' 'Sierra Leone'
 'Mauritania' 'Kenya' 'Djibouti' 'Armenia' 'Botswana' 'Myanmar' 'Georgia'
 'Malawi' 'Sri Lanka' 'Cameroon' 'Bulgaria' 'Egypt' 'Yemen' 'Angola'
 'Mali' 'Congo (Brazzaville)' 'Comoros' 'Uganda' 'Senegal' 'Gabon' 'Niger'
 'Cambodia' 'Tanzania' 'Madagascar' 'Central African Republic' 'Chad'
 'Guinea' 'Ivory Coast' 'Burkina Faso' 'Afghanistan' 'Rwanda' 'Benin'
 'Syria' 'Burundi' 'Togo']
158


158
RangeIndex(start=0, stop=158, step=1)
count     158
unique      4
top        []
freq      134
Name: country, dtype: object


24
(8, 'New Zealand', ' ')
(11, 'Costa Rica', ' ')
(14, 'United States', ' ')
(19, 'United Arab Emirates', ' ', ' ')
(20, 'United Kingdom', ' ')
(30, 'Czech Republic', ' ')
(34, 'Saudi Arabia', ' ')
(40, 'Trinidad and Tobago', ' ', ' ')
(41, 'El Salvador', ' ')
(46, 'South Korea', ' ')
(65, 'North Cyprus', ' ')
(71, 'Hong Kong', ' ')
(90, 'Somaliland region', ' ')
(95, 'Bosnia and Herzegovina', ' ', ' ')
(97, 'Dominican Republic', ' ')
(107, 'Palestinian Territories', ' ')
(112, 'South Africa', ' ')
(119, 'Congo (Kinshasa)', ' (', ')')
(122, 'Sierra Leone', ' ')
(131, 'Sri Lanka', ' ')
(138, 'Congo (Brazzaville)', ' (', ')')
(147, 'Central African Republic', ' ', ' ')
(150, 'Ivory Coast', ' ')
(151, 'Burkina Faso', ' ')

In [56]:
# Collecting, storing and presenting the values in the region column that contain non-alphabetic characters,
# referring to the data of year 2015.
values = find_present_non_word_values(data_table=data_table, column_name=region_column_name)

['Western Europe' 'North America and ANZ' 'Middle East and North Africa'
 'Latin America and Caribbean' 'Southeast Asia'
 'Central and Eastern Europe' 'East Asia'
 'Commonwealth of Independent States' 'Sub-Saharan Africa' 'South Asia']
10


158
RangeIndex(start=0, stop=158, step=1)
count           158
unique            4
top       [ ,  ,  ]
freq             55
Name: Regional indicator, dtype: object


158
(0, 'Western Europe', ' ')
(1, 'Western Europe', ' ')
(2, 'Western Europe', ' ')
(3, 'Western Europe', ' ')
(4, 'North America and ANZ', ' ', ' ', ' ')
(5, 'Western Europe', ' ')
(6, 'Western Europe', ' ')
(7, 'Western Europe', ' ')
(8, 'North America and ANZ', ' ', ' ', ' ')
(9, 'North America and ANZ', ' ', ' ', ' ')
(10, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(11, 'Latin America and Caribbean', ' ', ' ', ' ')
(12, 'Western Europe', ' ')
(13, 'Latin America and Caribbean', ' ', ' ', ' ')
(14, 'North America and ANZ', ' ', ' ', ' ')
(15, 'Latin America and Caribbean', ' ', ' ', ' ')
(16, 'Western Europe', ' ')
(17, 'Western Europe', ' ')
(18, 'Western Europe', ' ')
(19, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(20, 'Western Europe', ' ')
(21, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(22, 'Latin America and Caribbean', ' ', ' ', ' ')
(23, 'Southeast Asia', ' ')
(24, 'Latin America and Caribbean', ' ', ' ', ' ')
(25, 'Western Europe', ' ')
(26, 'Latin America and Caribbean', ' ', ' ', ' ')
(27, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(28, 'Western Europe', ' ')
(29, 'Latin America and Caribbean', ' ', ' ', ' ')
(30, 'Central and Eastern Europe', ' ', ' ', ' ')
(31, 'Latin America and Caribbean', ' ', ' ', ' ')
(32, 'Latin America and Caribbean', ' ', ' ', ' ')
(33, 'Southeast Asia', ' ')
(34, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(35, 'Western Europe', ' ')
(36, 'Western Europe', ' ')
(37, 'East Asia', ' ')
(38, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(39, 'Latin America and Caribbean', ' ', ' ', ' ')
(40, 'Latin America and Caribbean', ' ', ' ', ' ')
(41, 'Latin America and Caribbean', ' ', ' ', ' ')
(42, 'Latin America and Caribbean', ' ', ' ', ' ')
(43, 'Commonwealth of Independent States', ' ', ' ', ' ')
(44, 'Central and Eastern Europe', ' ', ' ', ' ')
(45, 'East Asia', ' ')
(46, 'East Asia', ' ')
(47, 'Latin America and Caribbean', ' ', ' ', ' ')
(48, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(49, 'Western Europe', ' ')
(50, 'Latin America and Caribbean', ' ', ' ', ' ')
(51, 'Commonwealth of Independent States', ' ', ' ', ' ')
(52, 'Latin America and Caribbean', ' ', ' ', ' ')
(53, 'Commonwealth of Independent States', ' ', ' ', ' ')
(54, 'Central and Eastern Europe', ' ', ' ', ' ')
(55, 'Central and Eastern Europe', ' ', ' ', ' ')
(56, 'Latin America and Caribbean', ' ', ' ', ' ')
(57, 'Latin America and Caribbean', ' ', ' ', ' ')
(58, 'Commonwealth of Independent States', ' ', ' ', ' ')
(59, 'Central and Eastern Europe', ' ', ' ', ' ')
(60, 'Southeast Asia', ' ')
(61, 'Central and Eastern Europe', ' ', ' ', ' ')
(62, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(63, 'Commonwealth of Independent States', ' ', ' ', ' ')
(64, 'Latin America and Caribbean', ' ', ' ', ' ')
(65, 'Western Europe', ' ')
(66, 'Western Europe', ' ')
(67, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(68, 'Central and Eastern Europe', ' ', ' ', ' ')
(69, 'Commonwealth of Independent States', ' ', ' ', ' ')
(70, 'Sub-Saharan Africa', '-', ' ')
(71, 'East Asia', ' ')
(72, 'Central and Eastern Europe', ' ', ' ', ' ')
(73, 'Southeast Asia', ' ')
(74, 'Southeast Asia', ' ')
(75, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(76, 'Commonwealth of Independent States', ' ', ' ', ' ')
(77, 'Sub-Saharan Africa', '-', ' ')
(78, 'South Asia', ' ')
(79, 'Commonwealth of Independent States', ' ', ' ', ' ')
(80, 'South Asia', ' ')
(81, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(82, 'Central and Eastern Europe', ' ', ' ', ' ')
(83, 'East Asia', ' ')
(84, 'Sub-Saharan Africa', '-', ' ')
(85, 'Central and Eastern Europe', ' ', ' ', ' ')
(86, 'Central and Eastern Europe', ' ', ' ', ' ')
(87, 'Western Europe', ' ')
(88, 'Central and Eastern Europe', ' ', ' ', ' ')
(89, 'Southeast Asia', ' ')
(90, 'Sub-Saharan Africa', '-', ' ')
(91, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(92, 'Central and Eastern Europe', ' ', ' ', ' ')
(93, 'Sub-Saharan Africa', '-', ' ')
(94, 'Central and Eastern Europe', ' ', ' ', ' ')
(95, 'Central and Eastern Europe', ' ', ' ', ' ')
(96, 'Sub-Saharan Africa', '-', ' ')
(97, 'Latin America and Caribbean', ' ', ' ', ' ')
(98, 'Southeast Asia', ' ')
(99, 'East Asia', ' ')
(100, 'Sub-Saharan Africa', '-', ' ')
(101, 'Western Europe', ' ')
(102, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(103, 'Central and Eastern Europe', ' ', ' ', ' ')
(104, 'Latin America and Caribbean', ' ', ' ', ' ')
(105, 'Commonwealth of Independent States', ' ', ' ', ' ')
(106, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(107, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(108, 'South Asia', ' ')
(109, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(110, 'Commonwealth of Independent States', ' ', ' ', ' ')
(111, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(112, 'Sub-Saharan Africa', '-', ' ')
(113, 'Sub-Saharan Africa', '-', ' ')
(114, 'Sub-Saharan Africa', '-', ' ')
(115, 'Sub-Saharan Africa', '-', ' ')
(116, 'South Asia', ' ')
(117, 'Sub-Saharan Africa', '-', ' ')
(118, 'Latin America and Caribbean', ' ', ' ', ' ')
(119, 'Sub-Saharan Africa', '-', ' ')
(120, 'South Asia', ' ')
(121, 'Sub-Saharan Africa', '-', ' ')
(122, 'Sub-Saharan Africa', '-', ' ')
(123, 'Sub-Saharan Africa', '-', ' ')
(124, 'Sub-Saharan Africa', '-', ' ')
(125, 'Sub-Saharan Africa', '-', ' ')
(126, 'Commonwealth of Independent States', ' ', ' ', ' ')
(127, 'Sub-Saharan Africa', '-', ' ')
(128, 'Southeast Asia', ' ')
(129, 'Commonwealth of Independent States', ' ', ' ', ' ')
(130, 'Sub-Saharan Africa', '-', ' ')
(131, 'South Asia', ' ')
(132, 'Sub-Saharan Africa', '-', ' ')
(133, 'Central and Eastern Europe', ' ', ' ', ' ')
(134, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(135, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(136, 'Sub-Saharan Africa', '-', ' ')
(137, 'Sub-Saharan Africa', '-', ' ')
(138, 'Sub-Saharan Africa', '-', ' ')
(139, 'Sub-Saharan Africa', '-', ' ')
(140, 'Sub-Saharan Africa', '-', ' ')
(141, 'Sub-Saharan Africa', '-', ' ')
(142, 'Sub-Saharan Africa', '-', ' ')
(143, 'Sub-Saharan Africa', '-', ' ')
(144, 'Southeast Asia', ' ')
(145, 'Sub-Saharan Africa', '-', ' ')
(146, 'Sub-Saharan Africa', '-', ' ')
(147, 'Sub-Saharan Africa', '-', ' ')
(148, 'Sub-Saharan Africa', '-', ' ')
(149, 'Sub-Saharan Africa', '-', ' ')
(150, 'Sub-Saharan Africa', '-', ' ')
(151, 'Sub-Saharan Africa', '-', ' ')
(152, 'South Asia', ' ')
(153, 'Sub-Saharan Africa', '-', ' ')
(154, 'Sub-Saharan Africa', '-', ' ')
(155, 'Middle East and North Africa', ' ', ' ', ' ', ' ')
(156, 'Sub-Saharan Africa', '-', ' ')
(157, 'Sub-Saharan Africa', '-', ' ')

In [57]:
# Presenting the unique values in the region column, to identify necessary changes.
list(data_table[region_column_name].unique())

['Western Europe',
 'North America and ANZ',
 'Middle East and North Africa',
 'Latin America and Caribbean',
 'Southeast Asia',
 'Central and Eastern Europe',
 'East Asia',
 'Commonwealth of Independent States',
 'Sub-Saharan Africa',
 'South Asia']

In [58]:
# Checking and presenting which non-alphabetic characters are contained among the values and
# the respective values to identify possible changes.
for i in range(len(values)):
    if len(values[i]) > 2:
        found = False
        for j in range(2, len(values[i])):
            if values[i][j] != " ":
                found = True
                break
        if found:
            value = str(values[i][0]) + " -- "
            value += values[i][1] + " -- "
            for j in range(2, len(values[i])):
                if values[i][j] != " ":
                    value += values[i][j] + " -- "
            value = value[0:-4]
            print(value)

70 -- Sub-Saharan Africa -- -
77 -- Sub-Saharan Africa -- -
84 -- Sub-Saharan Africa -- -
90 -- Sub-Saharan Africa -- -
93 -- Sub-Saharan Africa -- -
96 -- Sub-Saharan Africa -- -
100 -- Sub-Saharan Africa -- -
112 -- Sub-Saharan Africa -- -
113 -- Sub-Saharan Africa -- -
114 -- Sub-Saharan Africa -- -
115 -- Sub-Saharan Africa -- -
117 -- Sub-Saharan Africa -- -
119 -- Sub-Saharan Africa -- -
121 -- Sub-Saharan Africa -- -
122 -- Sub-Saharan Africa -- -
123 -- Sub-Saharan Africa -- -
124 -- Sub-Saharan Africa -- -
125 -- Sub-Saharan Africa -- -
127 -- Sub-Saharan Africa -- -
130 -- Sub-Saharan Africa -- -
132 -- Sub-Saharan Africa -- -
136 -- Sub-Saharan Africa -- -
137 -- Sub-Saharan Africa -- -
138 -- Sub-Saharan Africa -- -
139 -- Sub-Saharan Africa -- -
140 -- Sub-Saharan Africa -- -
141 -- Sub-Saharan Africa -- -
142 -- Sub-Saharan Africa -- -
143 -- Sub-Saharan Africa -- -
145 -- Sub-Saharan Africa -- -
146 -- Sub-Saharan Africa -- -
147 -- Sub-Saharan Africa -- -
148 -- Sub-Saharan Africa -- -
149 -- Sub-Saharan Africa -- -
150 -- Sub-Saharan Africa -- -
151 -- Sub-Saharan Africa -- -
153 -- Sub-Saharan Africa -- -
154 -- Sub-Saharan Africa -- -
156 -- Sub-Saharan Africa -- -
157 -- Sub-Saharan Africa -- -

In [59]:
# Storing country and region data of year 2015 in the result data structure.
table_results = include_data_table_results(data_table=data_table,
                                           result_columns=result_columns,
                                           country_column_name=country_column_name,
                                           region_column_name=region_column_name,
                                           table_results=table_results)

          COUNTRY                        REGION
0         Finland
1         Denmark
2         Iceland
3          Israel
4     Netherlands
...           ...                           ...
1364       Rwanda            Sub-Saharan Africa
1365        Benin            Sub-Saharan Africa
1366        Syria  Middle East and North Africa
1367      Burundi            Sub-Saharan Africa
1368         Togo            Sub-Saharan Africa

[1369 rows x 2 columns]

In [60]:
# Presenting the total unique values for regions in the result data structure.
total_countries = len(table_results["REGION"].unique())
print(total_countries)
print("\n")

# Presenting the total unique values for countries in the result data structure.
total_countries = len(table_results["COUNTRY"].unique())
print(total_countries)
print("\n")

# Identifing and presenting the total countries with empty regions among those regions associated with them.
count = 0
for country in table_results["COUNTRY"].unique():
    regions = list(table_results[(table_results["COUNTRY"] == country)]["REGION"].unique())
    for i in range(len(regions)):
        if regions[i] == "":
            count += 1
            break
print('Total countries with regions "":')
print(count)
print(total_countries - count)
print("\n")

# Identifing and presenting the total countries without any region associated with them.
count = 0
for country in table_results["COUNTRY"].unique():
    regions = list(table_results[(table_results["COUNTRY"] == country)]["REGION"].unique())
    if len(regions) == 0:
        count += 1
print("Total countries without regions:")
print(count)
print(total_countries - count)
print("\n")

# Identifing and presenting the total countries with more than one region associated with them.
count = 0
for country in table_results["COUNTRY"].unique():
    regions = list(table_results[(table_results["COUNTRY"] == country)]["REGION"].unique())
    if len(regions) > 1:
        count += 1
print("Total countries with more than one region:")
print(count)
print(total_countries - count)
print("\n")

# Identifing and presenting the maximum total regions associated to a single country.
count = -1
for country in table_results["COUNTRY"].unique():
    regions = list(table_results[(table_results["COUNTRY"] == country)]["REGION"].unique())
    if len(regions) > count:
        count = len(regions)
print("Maximum of regions associated with a single country:")
print(count)
print("\n")

# Presenting and saving in a text file the countries and regions associated with each one of them.
values_total_regions = list(range(count, 0, -1))
count = 0
value = ""
for total_regions in values_total_regions:
    for country in table_results["COUNTRY"].unique():
        regions = list(table_results[(table_results["COUNTRY"] == country)]["REGION"].unique())
        if len(regions) == total_regions:
            count += 1
            value += "%3d" % count
            value += " - " + country + "(" + str(len(regions)) + "): "
            for i in range(len(regions)):
                if regions[i] != "":
                    value += str(regions[i]) + " -- "
            if value[len(value) - 4:len(value)] == " -- ":
                value = value[0:-4]
            value += "\n"
print(value)

file_name = path_output + "Values_Country_Region_1.txt"
file_country_region = open(file=file_name, mode="w")
file_country_region.write(value)
file_country_region.close()

11


176


Total countries with regions "":
172
4


Total countries without regions:
1
175


Total countries with more than one region:
162
14


Maximum of regions associated with a single country:
2


  1 - Finland(2): Western Europe
  2 - Denmark(2): Western Europe
  3 - Iceland(2): Western Europe
  4 - Israel(2): Middle East and North Africa
  5 - Netherlands(2): Western Europe
  6 - Sweden(2): Western Europe
  7 - Norway(2): Western Europe
  8 - Switzerland(2): Western Europe
  9 - Luxembourg(2): Western Europe
 10 - New Zealand(2): North America and ANZ
 11 - Austria(2): Western Europe
 12 - Australia(2): North America and ANZ
 13 - Canada(2): North America and ANZ
 14 - Ireland(2): Western Europe
 15 - United States(2): North America and ANZ
 16 - Germany(2): Western Europe
 17 - Belgium(2): Western Europe
 18 - United Kingdom(2): Western Europe
 19 - Lithuania(2): Central and Eastern Europe
 20 - France(2): Western Europe
 21 - Slovenia(2): Central and Eastern Europe
 22 - Costa Rica(2): Latin America and Caribbean
 23 - Romania(2): Central and Eastern Europe
 24 - Singapore(2): Southeast Asia
 25 - United Arab Emirates(2): Middle East and North Africa
 26 - Taiwan Province of China(2): East Asia
 27 - Uruguay(2): Latin America and Caribbean
 28 - Slovakia(2): Central and Eastern Europe
 29 - Saudi Arabia(2): Middle East and North Africa
 30 - Estonia(2): Central and Eastern Europe
 31 - Spain(2): Western Europe
 32 - Italy(2): Western Europe
 33 - Kosovo(2): Central and Eastern Europe
 34 - Chile(2): Latin America and Caribbean
 35 - Mexico(2): Latin America and Caribbean
 36 - Malta(2): Western Europe
 37 - Panama(2): Latin America and Caribbean
 38 - Poland(2): Central and Eastern Europe
 39 - Nicaragua(2): Latin America and Caribbean
 40 - Latvia(2): Central and Eastern Europe
 41 - Bahrain(2): Middle East and North Africa
 42 - Guatemala(2): Latin America and Caribbean
 43 - Kazakhstan(2): Commonwealth of Independent States
 44 - Serbia(2): Central and Eastern Europe
 45 - Cyprus(2): Western Europe
 46 - Japan(2): East Asia
 47 - Croatia(2): Central and Eastern Europe
 48 - Brazil(2): Latin America and Caribbean
 49 - El Salvador(2): Latin America and Caribbean
 50 - Hungary(2): Central and Eastern Europe
 51 - Argentina(2): Latin America and Caribbean
 52 - Honduras(2): Latin America and Caribbean
 53 - Uzbekistan(2): Commonwealth of Independent States
 54 - Malaysia(2): Southeast Asia
 55 - Portugal(2): Western Europe
 56 - South Korea(2): East Asia
 57 - Greece(2): Western Europe
 58 - Mauritius(2): Sub-Saharan Africa
 59 - Thailand(2): Southeast Asia
 60 - Mongolia(2): East Asia
 61 - Kyrgyzstan(2): Commonwealth of Independent States
 62 - Moldova(2): Commonwealth of Independent States
 63 - China(2): East Asia
 64 - Vietnam(2): Southeast Asia
 65 - Paraguay(2): Latin America and Caribbean
 66 - Montenegro(2): Central and Eastern Europe
 67 - Jamaica(2): Latin America and Caribbean
 68 - Bolivia(2): Latin America and Caribbean
 69 - Russia(2): Commonwealth of Independent States
 70 - Bosnia and Herzegovina(2): Central and Eastern Europe
 71 - Colombia(2): Latin America and Caribbean
 72 - Dominican Republic(2): Latin America and Caribbean
 73 - Ecuador(2): Latin America and Caribbean
 74 - Peru(2): Latin America and Caribbean
 75 - Philippines(2): Southeast Asia
 76 - Bulgaria(2): Central and Eastern Europe
 77 - Nepal(2): South Asia
 78 - Armenia(2): Commonwealth of Independent States
 79 - Tajikistan(2): Commonwealth of Independent States
 80 - Algeria(2): Middle East and North Africa
 81 - Hong Kong S.A.R. of China(2): East Asia
 82 - Albania(2): Central and Eastern Europe
 83 - Indonesia(2): Southeast Asia
 84 - South Africa(2): Sub-Saharan Africa
 85 - Congo (Brazzaville)(2): Sub-Saharan Africa
 86 - North Macedonia(2): Central and Eastern Europe
 87 - Venezuela(2): Latin America and Caribbean
 88 - Laos(2): Southeast Asia
 89 - Georgia(2): Commonwealth of Independent States
 90 - Guinea(2): Sub-Saharan Africa
 91 - Ukraine(2): Commonwealth of Independent States
 92 - Ivory Coast(2): Sub-Saharan Africa
 93 - Gabon(2): Sub-Saharan Africa
 94 - Nigeria(2): Sub-Saharan Africa
 95 - Cameroon(2): Sub-Saharan Africa
 96 - Mozambique(2): Sub-Saharan Africa
 97 - Iraq(2): Middle East and North Africa
 98 - Morocco(2): Middle East and North Africa
 99 - Iran(2): Middle East and North Africa
100 - Senegal(2): Sub-Saharan Africa
101 - Mauritania(2): Sub-Saharan Africa
102 - Burkina Faso(2): Sub-Saharan Africa
103 - Namibia(2): Sub-Saharan Africa
104 - Ghana(2): Sub-Saharan Africa
105 - Pakistan(2): South Asia
106 - Niger(2): Sub-Saharan Africa
107 - Tunisia(2): Middle East and North Africa
108 - Kenya(2): Sub-Saharan Africa
109 - Sri Lanka(2): South Asia
110 - Uganda(2): Sub-Saharan Africa
111 - Chad(2): Sub-Saharan Africa
112 - Cambodia(2): Southeast Asia
113 - Benin(2): Sub-Saharan Africa
114 - Myanmar(2): Southeast Asia
115 - Bangladesh(2): South Asia
116 - Gambia(2): Sub-Saharan Africa
117 - Mali(2): Sub-Saharan Africa
118 - Egypt(2): Middle East and North Africa
119 - Togo(2): Sub-Saharan Africa
120 - Jordan(2): Middle East and North Africa
121 - Ethiopia(2): Sub-Saharan Africa
122 - Liberia(2): Sub-Saharan Africa
123 - India(2): South Asia
124 - Madagascar(2): Sub-Saharan Africa
125 - Zambia(2): Sub-Saharan Africa
126 - Tanzania(2): Sub-Saharan Africa
127 - Comoros(2): Sub-Saharan Africa
128 - Malawi(2): Sub-Saharan Africa
129 - Botswana(2): Sub-Saharan Africa
130 - Congo (Kinshasa)(2): Sub-Saharan Africa
131 - Zimbabwe(2): Sub-Saharan Africa
132 - Sierra Leone(2): Sub-Saharan Africa
133 - Lebanon(2): Middle East and North Africa
134 - Afghanistan(2): South Asia
135 - Kuwait(2): Middle East and North Africa
136 - Belarus(2): Commonwealth of Independent States
137 - Turkmenistan(2): Commonwealth of Independent States
138 - North Cyprus(2): Western Europe
139 - Libya(2): Middle East and North Africa
140 - Azerbaijan(2): Commonwealth of Independent States
141 - Turkey(2): Middle East and North Africa
142 - Palestinian Territories(2): Middle East and North Africa
143 - Yemen(2): Middle East and North Africa
144 - Lesotho(2): Sub-Saharan Africa
145 - Rwanda(2): Sub-Saharan Africa
146 - Czech Republic(2): Central and Eastern Europe
147 - Swaziland(2): Sub-Saharan Africa
148 - Burundi(2): Sub-Saharan Africa
149 - Haiti(2): Latin America and Caribbean
150 - Trinidad and Tobago(2): Latin America and Caribbean
151 - Macedonia(2): Central and Eastern Europe
152 - Central African Republic(2): Sub-Saharan Africa
153 - South Sudan(2): Sub-Saharan Africa
154 - Qatar(2): Middle East and North Africa
155 - Bhutan(2): South Asia
156 - Syria(2): Middle East and North Africa
157 - Sudan(2): Sub-Saharan Africa
158 - Angola(2): Sub-Saharan Africa
159 - Taiwan(2): East Asia
160 - Suriname(2): Latin America and Caribbean
161 - Hong Kong(2): East Asia
162 - Somaliland region(2): Sub-Saharan Africa
163 - Czechia(1):
164 - State of Palestine(1):
165 - Turkiye(1):
166 - Congo(1):
167 - Kingdom of Eswatini(1):
168 - xx(1):
169 - Maldives(1): South Asia
170 - Somalia(1):
171 - Belize(1):
172 - Northern Cyprus(1):
173 - Puerto Rico(1):
174 - Oman(1): Middle East and North Africa
175 - Djibouti(1): Sub-Saharan Africa

In [61]:
# Checking and presenting the total occurrences of the country identified in the data as xx.
count = len(table_results[(table_results["COUNTRY"] == "xx")])
print(count)

1

In [62]:
# Selecting the region of each country that has more than one, where "" is one of them,
# and applying the Unknown value to the countries without any region.
for country in table_results["COUNTRY"].unique():
    regions = list(table_results[(table_results["COUNTRY"] == country)]["REGION"].unique())
    indices = list(table_results[(table_results["COUNTRY"] == country)].index)
    region = ""
    if (len(regions) == 1) and (regions[0] == ""):
        region = "Unknown"
    elif len(regions) > 0:
        for i in range(len(regions)):
            if regions[i] != "":
                region = regions[i]
                break
    # Adjusting the region of each country in the result data structure.
    if len(regions) > 0:
        table_results.loc[indices, "REGION"] = region

In [63]:
# Presenting and saving in a text file the countries and regions associated with each one of them.
count = 0
value = ""
for country in table_results["COUNTRY"].unique():
    regions = list(table_results[(table_results["COUNTRY"] == country)]["REGION"].unique())
    if len(regions) > 0:
        count += 1
        value += "%3d" % count
        value += " - " + country + "(" + str(len(regions)) + "): "
        for i in range(len(regions)):
            if regions[i] != "":
                value += str(regions[i]) + " -- "
        if value[len(value) - 4:len(value)] == " -- ":
            value = value[0:-4]
        value += "\n"
print(value)

file_name = path_output + "Values_Country_Region_2.txt"
file_country_region = open(file=file_name, mode="w")
file_country_region.write(value)
file_country_region.close()

  1 - Finland(1): Western Europe
  2 - Denmark(1): Western Europe
  3 - Iceland(1): Western Europe
  4 - Israel(1): Middle East and North Africa
  5 - Netherlands(1): Western Europe
  6 - Sweden(1): Western Europe
  7 - Norway(1): Western Europe
  8 - Switzerland(1): Western Europe
  9 - Luxembourg(1): Western Europe
 10 - New Zealand(1): North America and ANZ
 11 - Austria(1): Western Europe
 12 - Australia(1): North America and ANZ
 13 - Canada(1): North America and ANZ
 14 - Ireland(1): Western Europe
 15 - United States(1): North America and ANZ
 16 - Germany(1): Western Europe
 17 - Belgium(1): Western Europe
 18 - Czechia(1): Unknown
 19 - United Kingdom(1): Western Europe
 20 - Lithuania(1): Central and Eastern Europe
 21 - France(1): Western Europe
 22 - Slovenia(1): Central and Eastern Europe
 23 - Costa Rica(1): Latin America and Caribbean
 24 - Romania(1): Central and Eastern Europe
 25 - Singapore(1): Southeast Asia
 26 - United Arab Emirates(1): Middle East and North Africa
 27 - Taiwan Province of China(1): East Asia
 28 - Uruguay(1): Latin America and Caribbean
 29 - Slovakia(1): Central and Eastern Europe
 30 - Saudi Arabia(1): Middle East and North Africa
 31 - Estonia(1): Central and Eastern Europe
 32 - Spain(1): Western Europe
 33 - Italy(1): Western Europe
 34 - Kosovo(1): Central and Eastern Europe
 35 - Chile(1): Latin America and Caribbean
 36 - Mexico(1): Latin America and Caribbean
 37 - Malta(1): Western Europe
 38 - Panama(1): Latin America and Caribbean
 39 - Poland(1): Central and Eastern Europe
 40 - Nicaragua(1): Latin America and Caribbean
 41 - Latvia(1): Central and Eastern Europe
 42 - Bahrain(1): Middle East and North Africa
 43 - Guatemala(1): Latin America and Caribbean
 44 - Kazakhstan(1): Commonwealth of Independent States
 45 - Serbia(1): Central and Eastern Europe
 46 - Cyprus(1): Western Europe
 47 - Japan(1): East Asia
 48 - Croatia(1): Central and Eastern Europe
 49 - Brazil(1): Latin America and Caribbean
 50 - El Salvador(1): Latin America and Caribbean
 51 - Hungary(1): Central and Eastern Europe
 52 - Argentina(1): Latin America and Caribbean
 53 - Honduras(1): Latin America and Caribbean
 54 - Uzbekistan(1): Commonwealth of Independent States
 55 - Malaysia(1): Southeast Asia
 56 - Portugal(1): Western Europe
 57 - South Korea(1): East Asia
 58 - Greece(1): Western Europe
 59 - Mauritius(1): Sub-Saharan Africa
 60 - Thailand(1): Southeast Asia
 61 - Mongolia(1): East Asia
 62 - Kyrgyzstan(1): Commonwealth of Independent States
 63 - Moldova(1): Commonwealth of Independent States
 64 - China(1): East Asia
 65 - Vietnam(1): Southeast Asia
 66 - Paraguay(1): Latin America and Caribbean
 67 - Montenegro(1): Central and Eastern Europe
 68 - Jamaica(1): Latin America and Caribbean
 69 - Bolivia(1): Latin America and Caribbean
 70 - Russia(1): Commonwealth of Independent States
 71 - Bosnia and Herzegovina(1): Central and Eastern Europe
 72 - Colombia(1): Latin America and Caribbean
 73 - Dominican Republic(1): Latin America and Caribbean
 74 - Ecuador(1): Latin America and Caribbean
 75 - Peru(1): Latin America and Caribbean
 76 - Philippines(1): Southeast Asia
 77 - Bulgaria(1): Central and Eastern Europe
 78 - Nepal(1): South Asia
 79 - Armenia(1): Commonwealth of Independent States
 80 - Tajikistan(1): Commonwealth of Independent States
 81 - Algeria(1): Middle East and North Africa
 82 - Hong Kong S.A.R. of China(1): East Asia
 83 - Albania(1): Central and Eastern Europe
 84 - Indonesia(1): Southeast Asia
 85 - South Africa(1): Sub-Saharan Africa
 86 - Congo (Brazzaville)(1): Sub-Saharan Africa
 87 - North Macedonia(1): Central and Eastern Europe
 88 - Venezuela(1): Latin America and Caribbean
 89 - Laos(1): Southeast Asia
 90 - Georgia(1): Commonwealth of Independent States
 91 - Guinea(1): Sub-Saharan Africa
 92 - Ukraine(1): Commonwealth of Independent States
 93 - Ivory Coast(1): Sub-Saharan Africa
 94 - Gabon(1): Sub-Saharan Africa
 95 - Nigeria(1): Sub-Saharan Africa
 96 - Cameroon(1): Sub-Saharan Africa
 97 - Mozambique(1): Sub-Saharan Africa
 98 - Iraq(1): Middle East and North Africa
 99 - State of Palestine(1): Unknown
100 - Morocco(1): Middle East and North Africa
101 - Iran(1): Middle East and North Africa
102 - Senegal(1): Sub-Saharan Africa
103 - Mauritania(1): Sub-Saharan Africa
104 - Burkina Faso(1): Sub-Saharan Africa
105 - Namibia(1): Sub-Saharan Africa
106 - Turkiye(1): Unknown
107 - Ghana(1): Sub-Saharan Africa
108 - Pakistan(1): South Asia
109 - Niger(1): Sub-Saharan Africa
110 - Tunisia(1): Middle East and North Africa
111 - Kenya(1): Sub-Saharan Africa
112 - Sri Lanka(1): South Asia
113 - Uganda(1): Sub-Saharan Africa
114 - Chad(1): Sub-Saharan Africa
115 - Cambodia(1): Southeast Asia
116 - Benin(1): Sub-Saharan Africa
117 - Myanmar(1): Southeast Asia
118 - Bangladesh(1): South Asia
119 - Gambia(1): Sub-Saharan Africa
120 - Mali(1): Sub-Saharan Africa
121 - Egypt(1): Middle East and North Africa
122 - Togo(1): Sub-Saharan Africa
123 - Jordan(1): Middle East and North Africa
124 - Ethiopia(1): Sub-Saharan Africa
125 - Liberia(1): Sub-Saharan Africa
126 - India(1): South Asia
127 - Madagascar(1): Sub-Saharan Africa
128 - Zambia(1): Sub-Saharan Africa
129 - Tanzania(1): Sub-Saharan Africa
130 - Comoros(1): Sub-Saharan Africa
131 - Malawi(1): Sub-Saharan Africa
132 - Botswana(1): Sub-Saharan Africa
133 - Congo (Kinshasa)(1): Sub-Saharan Africa
134 - Zimbabwe(1): Sub-Saharan Africa
135 - Sierra Leone(1): Sub-Saharan Africa
136 - Lebanon(1): Middle East and North Africa
137 - Afghanistan(1): South Asia
138 - Kuwait(1): Middle East and North Africa
139 - Belarus(1): Commonwealth of Independent States
140 - Turkmenistan(1): Commonwealth of Independent States
141 - North Cyprus(1): Western Europe
142 - Libya(1): Middle East and North Africa
143 - Azerbaijan(1): Commonwealth of Independent States
144 - Congo(1): Unknown
145 - Turkey(1): Middle East and North Africa
146 - Palestinian Territories(1): Middle East and North Africa
147 - Kingdom of Eswatini(1): Unknown
148 - Yemen(1): Middle East and North Africa
149 - Lesotho(1): Sub-Saharan Africa
150 - Rwanda(1): Sub-Saharan Africa
151 - xx(1): Unknown
152 - Czech Republic(1): Central and Eastern Europe
153 - Maldives(1): South Asia
154 - Swaziland(1): Sub-Saharan Africa
155 - Burundi(1): Sub-Saharan Africa
156 - Haiti(1): Latin America and Caribbean
157 - Trinidad and Tobago(1): Latin America and Caribbean
158 - Macedonia(1): Central and Eastern Europe
159 - Central African Republic(1): Sub-Saharan Africa
160 - South Sudan(1): Sub-Saharan Africa
161 - Qatar(1): Middle East and North Africa
162 - Bhutan(1): South Asia
163 - Somalia(1): Unknown
164 - Syria(1): Middle East and North Africa
165 - Belize(1): Unknown
166 - Northern Cyprus(1): Unknown
167 - Sudan(1): Sub-Saharan Africa
168 - Angola(1): Sub-Saharan Africa
169 - Puerto Rico(1): Unknown
170 - Taiwan(1): East Asia
171 - Suriname(1): Latin America and Caribbean
172 - Hong Kong(1): East Asia
173 - Somaliland region(1): Sub-Saharan Africa
174 - Oman(1): Middle East and North Africa
175 - Djibouti(1): Sub-Saharan Africa

In [64]:
# Comparing the regions of each country between the two saved files, aiming to identify possible differences between them.
# It is expected that the files are different only for countries that did not have any region.
input_file = open(path_output + "Values_Country_Region_1.txt", "r")
file1 = input_file.readlines()
input_file.close()

input_file = open(path_output + "Values_Country_Region_2.txt", "r")
file2 = input_file.readlines()
input_file.close()

different_countries = []
different_region_1 = []
different_region_2 = []
for i in range(len(file1)):
    for index in range(len(file1[i])):
        if file1[i][index] == ":":
            break
    country1 = file1[i][6:index-3]
    region1 = file1[i][index+2:len(file1[i])]
    
    for j in range(len(file2)):
        for index in range(len(file2[j])):
            if file2[j][index] == ":":
                break
        country2 = file2[j][6:index-3]
        region2 = file2[j][index+2:len(file2[j])]

        if country2 == country1:
            if region2 != region1:
                different_countries.append(country1)
                different_region_1.append(region1)
                different_region_2.append(region2)
            break

if len(different_countries) > 0:
    for i in range(len(different_countries)):
        value = different_countries[i] + " - "
        value += different_region_1[i][0:len(different_region_1[i])-2] + " - " #Removing the special char \n from the final string
        value += different_region_2[i][0:len(different_region_2[i])-2]
        print(value)

Czechia -  - Unknow
State of Palestine -  - Unknow
Turkiye -  - Unknow
Congo -  - Unknow
Kingdom of Eswatini -  - Unknow
xx -  - Unknow
Somalia -  - Unknow
Belize -  - Unknow
Northern Cyprus -  - Unknow
Puerto Rico -  - Unknow

In [65]:
# Removing possible records with nan values in the result data structure.
table_results.dropna(axis=0, how="any", inplace=True)
table_results.index = range(len(table_results))

# Removing the record referring to the country with value identified as xx.
indices = list(table_results[(table_results["COUNTRY"] == "xx")].index)
table_results.drop(index=indices, inplace=True)
table_results.index = range(len(table_results))

# Removing repetition of each country-region pair in the result data structure.
for country in table_results["COUNTRY"].unique():
    indices = list(table_results[(table_results["COUNTRY"] == country)].index)
    if len(indices) > 1:
        indices = indices[1:len(indices)]
        table_results.drop(index=indices, inplace=True)
        table_results.index = range(len(table_results))

# Presenting the total number of records in the result data structure and it content.
print(len(table_results))
print(table_results)

# Saving the analysis result data structure in a text file.
file_name = path_output + "Table_Country_Region.csv"
table_results.to_csv(path_or_buf=file_name, sep=delimiter_file_result, index=False)

174
               COUNTRY                        REGION
0              Finland                Western Europe
1              Denmark                Western Europe
2              Iceland                Western Europe
3               Israel  Middle East and North Africa
4          Netherlands                Western Europe
..                 ...                           ...
169           Suriname   Latin America and Caribbean
170          Hong Kong                     East Asia
171  Somaliland region            Sub-Saharan Africa
172               Oman  Middle East and North Africa
173           Djibouti            Sub-Saharan Africa

[174 rows x 2 columns]